// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.1
// source: pkg/condition/ci_condition.proto

package condition

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CIName struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CIName) Reset() {
	*x = CIName{}
	mi := &file_pkg_condition_ci_condition_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CIName) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CIName) ProtoMessage() {}

func (x *CIName) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_condition_ci_condition_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CIName.ProtoReflect.Descriptor instead.
func (*CIName) Descriptor() ([]byte, []int) {
	return file_pkg_condition_ci_condition_proto_rawDescGZIP(), []int{0}
}

type CIVersion struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CIVersion) Reset() {
	*x = CIVersion{}
	mi := &file_pkg_condition_ci_condition_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CIVersion) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CIVersion) ProtoMessage() {}

func (x *CIVersion) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_condition_ci_condition_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CIVersion.ProtoReflect.Descriptor instead.
func (*CIVersion) Descriptor() ([]byte, []int) {
	return file_pkg_condition_ci_condition_proto_rawDescGZIP(), []int{1}
}

type RunCondition struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RunCondition) Reset() {
	*x = RunCondition{}
	mi := &file_pkg_condition_ci_condition_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RunCondition) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RunCondition) ProtoMessage() {}

func (x *RunCondition) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_condition_ci_condition_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RunCondition.ProtoReflect.Descriptor instead.
func (*RunCondition) Descriptor() ([]byte, []int) {
	return file_pkg_condition_ci_condition_proto_rawDescGZIP(), []int{2}
}

type GetCurrentBranch struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCurrentBranch) Reset() {
	*x = GetCurrentBranch{}
	mi := &file_pkg_condition_ci_condition_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCurrentBranch) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCurrentBranch) ProtoMessage() {}

func (x *GetCurrentBranch) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_condition_ci_condition_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCurrentBranch.ProtoReflect.Descriptor instead.
func (*GetCurrentBranch) Descriptor() ([]byte, []int) {
	return file_pkg_condition_ci_condition_proto_rawDescGZIP(), []int{3}
}

type GetCurrentSHA struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCurrentSHA) Reset() {
	*x = GetCurrentSHA{}
	mi := &file_pkg_condition_ci_condition_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCurrentSHA) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCurrentSHA) ProtoMessage() {}

func (x *GetCurrentSHA) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_condition_ci_condition_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCurrentSHA.ProtoReflect.Descriptor instead.
func (*GetCurrentSHA) Descriptor() ([]byte, []int) {
	return file_pkg_condition_ci_condition_proto_rawDescGZIP(), []int{4}
}

type CIName_Request struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CIName_Request) Reset() {
	*x = CIName_Request{}
	mi := &file_pkg_condition_ci_condition_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CIName_Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CIName_Request) ProtoMessage() {}

func (x *CIName_Request) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_condition_ci_condition_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CIName_Request.ProtoReflect.Descriptor instead.
func (*CIName_Request) Descriptor() ([]byte, []int) {
	return file_pkg_condition_ci_condition_proto_rawDescGZIP(), []int{0, 0}
}

type CIName_Response struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CIName_Response) Reset() {
	*x = CIName_Response{}
	mi := &file_pkg_condition_ci_condition_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CIName_Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CIName_Response) ProtoMessage() {}

func (x *CIName_Response) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_condition_ci_condition_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CIName_Response.ProtoReflect.Descriptor instead.
func (*CIName_Response) Descriptor() ([]byte, []int) {
	return file_pkg_condition_ci_condition_proto_rawDescGZIP(), []int{0, 1}
}

func (x *CIName_Response) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type CIVersion_Request struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CIVersion_Request) Reset() {
	*x = CIVersion_Request{}
	mi := &file_pkg_condition_ci_condition_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CIVersion_Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CIVersion_Request) ProtoMessage() {}

func (x *CIVersion_Request) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_condition_ci_condition_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CIVersion_Request.ProtoReflect.Descriptor instead.
func (*CIVersion_Request) Descriptor() ([]byte, []int) {
	return file_pkg_condition_ci_condition_proto_rawDescGZIP(), []int{1, 0}
}

type CIVersion_Response struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Version       string                 `protobuf:"bytes,1,opt,name=version,proto3" json:"version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CIVersion_Response) Reset() {
	*x = CIVersion_Response{}
	mi := &file_pkg_condition_ci_condition_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CIVersion_Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CIVersion_Response) ProtoMessage() {}

func (x *CIVersion_Response) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_condition_ci_condition_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CIVersion_Response.ProtoReflect.Descriptor instead.
func (*CIVersion_Response) Descriptor() ([]byte, []int) {
	return file_pkg_condition_ci_condition_proto_rawDescGZIP(), []int{1, 1}
}

func (x *CIVersion_Response) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

type RunCondition_Request struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Value         map[string]string      `protobuf:"bytes,1,rep,name=value,proto3" json:"value,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RunCondition_Request) Reset() {
	*x = RunCondition_Request{}
	mi := &file_pkg_condition_ci_condition_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RunCondition_Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RunCondition_Request) ProtoMessage() {}

func (x *RunCondition_Request) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_condition_ci_condition_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RunCondition_Request.ProtoReflect.Descriptor instead.
func (*RunCondition_Request) Descriptor() ([]byte, []int) {
	return file_pkg_condition_ci_condition_proto_rawDescGZIP(), []int{2, 0}
}

func (x *RunCondition_Request) GetValue() map[string]string {
	if x != nil {
		return x.Value
	}
	return nil
}

type RunCondition_Response struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Error         string                 `protobuf:"bytes,1,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RunCondition_Response) Reset() {
	*x = RunCondition_Response{}
	mi := &file_pkg_condition_ci_condition_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RunCondition_Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RunCondition_Response) ProtoMessage() {}

func (x *RunCondition_Response) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_condition_ci_condition_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RunCondition_Response.ProtoReflect.Descriptor instead.
func (*RunCondition_Response) Descriptor() ([]byte, []int) {
	return file_pkg_condition_ci_condition_proto_rawDescGZIP(), []int{2, 1}
}

func (x *RunCondition_Response) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type GetCurrentBranch_Request struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCurrentBranch_Request) Reset() {
	*x = GetCurrentBranch_Request{}
	mi := &file_pkg_condition_ci_condition_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCurrentBranch_Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCurrentBranch_Request) ProtoMessage() {}

func (x *GetCurrentBranch_Request) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_condition_ci_condition_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCurrentBranch_Request.ProtoReflect.Descriptor instead.
func (*GetCurrentBranch_Request) Descriptor() ([]byte, []int) {
	return file_pkg_condition_ci_condition_proto_rawDescGZIP(), []int{3, 0}
}

type GetCurrentBranch_Response struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Value         string                 `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCurrentBranch_Response) Reset() {
	*x = GetCurrentBranch_Response{}
	mi := &file_pkg_condition_ci_condition_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCurrentBranch_Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCurrentBranch_Response) ProtoMessage() {}

func (x *GetCurrentBranch_Response) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_condition_ci_condition_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCurrentBranch_Response.ProtoReflect.Descriptor instead.
func (*GetCurrentBranch_Response) Descriptor() ([]byte, []int) {
	return file_pkg_condition_ci_condition_proto_rawDescGZIP(), []int{3, 1}
}

func (x *GetCurrentBranch_Response) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

type GetCurrentSHA_Request struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCurrentSHA_Request) Reset() {
	*x = GetCurrentSHA_Request{}
	mi := &file_pkg_condition_ci_condition_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCurrentSHA_Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCurrentSHA_Request) ProtoMessage() {}

func (x *GetCurrentSHA_Request) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_condition_ci_condition_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCurrentSHA_Request.ProtoReflect.Descriptor instead.
func (*GetCurrentSHA_Request) Descriptor() ([]byte, []int) {
	return file_pkg_condition_ci_condition_proto_rawDescGZIP(), []int{4, 0}
}

type GetCurrentSHA_Response struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Value         string                 `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCurrentSHA_Response) Reset() {
	*x = GetCurrentSHA_Response{}
	mi := &file_pkg_condition_ci_condition_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCurrentSHA_Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCurrentSHA_Response) ProtoMessage() {}

func (x *GetCurrentSHA_Response) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_condition_ci_condition_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCurrentSHA_Response.ProtoReflect.Descriptor instead.
func (*GetCurrentSHA_Response) Descriptor() ([]byte, []int) {
	return file_pkg_condition_ci_condition_proto_rawDescGZIP(), []int{4, 1}
}

func (x *GetCurrentSHA_Response) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

var File_pkg_condition_ci_condition_proto protoreflect.FileDescriptor

const file_pkg_condition_ci_condition_proto_rawDesc = "" +
	"\n" +
	" pkg/condition/ci_condition.proto\"3\n" +
	"\x06CIName\x1a\t\n" +
	"\aRequest\x1a\x1e\n" +
	"\bResponse\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\"<\n" +
	"\tCIVersion\x1a\t\n" +
	"\aRequest\x1a$\n" +
	"\bResponse\x12\x18\n" +
	"\aversion\x18\x01 \x01(\tR\aversion\"\xad\x01\n" +
	"\fRunCondition\x1a{\n" +
	"\aRequest\x126\n" +
	"\x05value\x18\x01 \x03(\v2 .RunCondition.Request.ValueEntryR\x05value\x1a8\n" +
	"\n" +
	"ValueEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\x1a \n" +
	"\bResponse\x12\x14\n" +
	"\x05error\x18\x01 \x01(\tR\x05error\"?\n" +
	"\x10GetCurrentBranch\x1a\t\n" +
	"\aRequest\x1a \n" +
	"\bResponse\x12\x14\n" +
	"\x05value\x18\x01 \x01(\tR\x05value\"<\n" +
	"\rGetCurrentSHA\x1a\t\n" +
	"\aRequest\x1a \n" +
	"\bResponse\x12\x14\n" +
	"\x05value\x18\x01 \x01(\tR\x05value2\xbe\x02\n" +
	"\x11CIConditionPlugin\x12)\n" +
	"\x04Name\x12\x0f.CIName.Request\x1a\x10.CIName.Response\x122\n" +
	"\aVersion\x12\x12.CIVersion.Request\x1a\x13.CIVersion.Response\x12=\n" +
	"\fRunCondition\x12\x15.RunCondition.Request\x1a\x16.RunCondition.Response\x12I\n" +
	"\x10GetCurrentBranch\x12\x19.GetCurrentBranch.Request\x1a\x1a.GetCurrentBranch.Response\x12@\n" +
	"\rGetCurrentSHA\x12\x16.GetCurrentSHA.Request\x1a\x17.GetCurrentSHA.ResponseBBZ@github.com/go-semantic-release/semantic-release/v2/pkg/conditionb\x06proto3"

var (
	file_pkg_condition_ci_condition_proto_rawDescOnce sync.Once
	file_pkg_condition_ci_condition_proto_rawDescData []byte
)

func file_pkg_condition_ci_condition_proto_rawDescGZIP() []byte {
	file_pkg_condition_ci_condition_proto_rawDescOnce.Do(func() {
		file_pkg_condition_ci_condition_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pkg_condition_ci_condition_proto_rawDesc), len(file_pkg_condition_ci_condition_proto_rawDesc)))
	})
	return file_pkg_condition_ci_condition_proto_rawDescData
}

var file_pkg_condition_ci_condition_proto_msgTypes = make([]protoimpl.MessageInfo, 16)
var file_pkg_condition_ci_condition_proto_goTypes = []any{
	(*CIName)(nil),                    // 0: CIName
	(*CIVersion)(nil),                 // 1: CIVersion
	(*RunCondition)(nil),              // 2: RunCondition
	(*GetCurrentBranch)(nil),          // 3: GetCurrentBranch
	(*GetCurrentSHA)(nil),             // 4: GetCurrentSHA
	(*CIName_Request)(nil),            // 5: CIName.Request
	(*CIName_Response)(nil),           // 6: CIName.Response
	(*CIVersion_Request)(nil),         // 7: CIVersion.Request
	(*CIVersion_Response)(nil),        // 8: CIVersion.Response
	(*RunCondition_Request)(nil),      // 9: RunCondition.Request
	(*RunCondition_Response)(nil),     // 10: RunCondition.Response
	nil,                               // 11: RunCondition.Request.ValueEntry
	(*GetCurrentBranch_Request)(nil),  // 12: GetCurrentBranch.Request
	(*GetCurrentBranch_Response)(nil), // 13: GetCurrentBranch.Response
	(*GetCurrentSHA_Request)(nil),     // 14: GetCurrentSHA.Request
	(*GetCurrentSHA_Response)(nil),    // 15: GetCurrentSHA.Response
}
var file_pkg_condition_ci_condition_proto_depIdxs = []int32{
	11, // 0: RunCondition.Request.value:type_name -> RunCondition.Request.ValueEntry
	5,  // 1: CIConditionPlugin.Name:input_type -> CIName.Request
	7,  // 2: CIConditionPlugin.Version:input_type -> CIVersion.Request
	9,  // 3: CIConditionPlugin.RunCondition:input_type -> RunCondition.Request
	12, // 4: CIConditionPlugin.GetCurrentBranch:input_type -> GetCurrentBranch.Request
	14, // 5: CIConditionPlugin.GetCurrentSHA:input_type -> GetCurrentSHA.Request
	6,  // 6: CIConditionPlugin.Name:output_type -> CIName.Response
	8,  // 7: CIConditionPlugin.Version:output_type -> CIVersion.Response
	10, // 8: CIConditionPlugin.RunCondition:output_type -> RunCondition.Response
	13, // 9: CIConditionPlugin.GetCurrentBranch:output_type -> GetCurrentBranch.Response
	15, // 10: CIConditionPlugin.GetCurrentSHA:output_type -> GetCurrentSHA.Response
	6,  // [6:11] is the sub-list for method output_type
	1,  // [1:6] is the sub-list for method input_type
	1,  // [1:1] is the sub-list for extension type_name
	1,  // [1:1] is the sub-list for extension extendee
	0,  // [0:1] is the sub-list for field type_name
}

func init() { file_pkg_condition_ci_condition_proto_init() }
func file_pkg_condition_ci_condition_proto_init() {
	if File_pkg_condition_ci_condition_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pkg_condition_ci_condition_proto_rawDesc), len(file_pkg_condition_ci_condition_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   16,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pkg_condition_ci_condition_proto_goTypes,
		DependencyIndexes: file_pkg_condition_ci_condition_proto_depIdxs,
		MessageInfos:      file_pkg_condition_ci_condition_proto_msgTypes,
	}.Build()
	File_pkg_condition_ci_condition_proto = out.File
	file_pkg_condition_ci_condition_proto_goTypes = nil
	file_pkg_condition_ci_condition_proto_depIdxs = nil
}
