// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.1
// source: pkg/updater/updater.proto

package updater

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type FilesUpdaterInit struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FilesUpdaterInit) Reset() {
	*x = FilesUpdaterInit{}
	mi := &file_pkg_updater_updater_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FilesUpdaterInit) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FilesUpdaterInit) ProtoMessage() {}

func (x *FilesUpdaterInit) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_updater_updater_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FilesUpdaterInit.ProtoReflect.Descriptor instead.
func (*FilesUpdaterInit) Descriptor() ([]byte, []int) {
	return file_pkg_updater_updater_proto_rawDescGZIP(), []int{0}
}

type FilesUpdaterName struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FilesUpdaterName) Reset() {
	*x = FilesUpdaterName{}
	mi := &file_pkg_updater_updater_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FilesUpdaterName) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FilesUpdaterName) ProtoMessage() {}

func (x *FilesUpdaterName) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_updater_updater_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FilesUpdaterName.ProtoReflect.Descriptor instead.
func (*FilesUpdaterName) Descriptor() ([]byte, []int) {
	return file_pkg_updater_updater_proto_rawDescGZIP(), []int{1}
}

type FilesUpdaterVersion struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FilesUpdaterVersion) Reset() {
	*x = FilesUpdaterVersion{}
	mi := &file_pkg_updater_updater_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FilesUpdaterVersion) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FilesUpdaterVersion) ProtoMessage() {}

func (x *FilesUpdaterVersion) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_updater_updater_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FilesUpdaterVersion.ProtoReflect.Descriptor instead.
func (*FilesUpdaterVersion) Descriptor() ([]byte, []int) {
	return file_pkg_updater_updater_proto_rawDescGZIP(), []int{2}
}

type FilesUpdaterForFiles struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FilesUpdaterForFiles) Reset() {
	*x = FilesUpdaterForFiles{}
	mi := &file_pkg_updater_updater_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FilesUpdaterForFiles) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FilesUpdaterForFiles) ProtoMessage() {}

func (x *FilesUpdaterForFiles) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_updater_updater_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FilesUpdaterForFiles.ProtoReflect.Descriptor instead.
func (*FilesUpdaterForFiles) Descriptor() ([]byte, []int) {
	return file_pkg_updater_updater_proto_rawDescGZIP(), []int{3}
}

type FilesUpdaterApply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FilesUpdaterApply) Reset() {
	*x = FilesUpdaterApply{}
	mi := &file_pkg_updater_updater_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FilesUpdaterApply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FilesUpdaterApply) ProtoMessage() {}

func (x *FilesUpdaterApply) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_updater_updater_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FilesUpdaterApply.ProtoReflect.Descriptor instead.
func (*FilesUpdaterApply) Descriptor() ([]byte, []int) {
	return file_pkg_updater_updater_proto_rawDescGZIP(), []int{4}
}

type FilesUpdaterInit_Request struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Config        map[string]string      `protobuf:"bytes,1,rep,name=config,proto3" json:"config,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FilesUpdaterInit_Request) Reset() {
	*x = FilesUpdaterInit_Request{}
	mi := &file_pkg_updater_updater_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FilesUpdaterInit_Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FilesUpdaterInit_Request) ProtoMessage() {}

func (x *FilesUpdaterInit_Request) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_updater_updater_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FilesUpdaterInit_Request.ProtoReflect.Descriptor instead.
func (*FilesUpdaterInit_Request) Descriptor() ([]byte, []int) {
	return file_pkg_updater_updater_proto_rawDescGZIP(), []int{0, 0}
}

func (x *FilesUpdaterInit_Request) GetConfig() map[string]string {
	if x != nil {
		return x.Config
	}
	return nil
}

type FilesUpdaterInit_Response struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Error         string                 `protobuf:"bytes,1,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FilesUpdaterInit_Response) Reset() {
	*x = FilesUpdaterInit_Response{}
	mi := &file_pkg_updater_updater_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FilesUpdaterInit_Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FilesUpdaterInit_Response) ProtoMessage() {}

func (x *FilesUpdaterInit_Response) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_updater_updater_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FilesUpdaterInit_Response.ProtoReflect.Descriptor instead.
func (*FilesUpdaterInit_Response) Descriptor() ([]byte, []int) {
	return file_pkg_updater_updater_proto_rawDescGZIP(), []int{0, 1}
}

func (x *FilesUpdaterInit_Response) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type FilesUpdaterName_Request struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FilesUpdaterName_Request) Reset() {
	*x = FilesUpdaterName_Request{}
	mi := &file_pkg_updater_updater_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FilesUpdaterName_Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FilesUpdaterName_Request) ProtoMessage() {}

func (x *FilesUpdaterName_Request) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_updater_updater_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FilesUpdaterName_Request.ProtoReflect.Descriptor instead.
func (*FilesUpdaterName_Request) Descriptor() ([]byte, []int) {
	return file_pkg_updater_updater_proto_rawDescGZIP(), []int{1, 0}
}

type FilesUpdaterName_Response struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FilesUpdaterName_Response) Reset() {
	*x = FilesUpdaterName_Response{}
	mi := &file_pkg_updater_updater_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FilesUpdaterName_Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FilesUpdaterName_Response) ProtoMessage() {}

func (x *FilesUpdaterName_Response) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_updater_updater_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FilesUpdaterName_Response.ProtoReflect.Descriptor instead.
func (*FilesUpdaterName_Response) Descriptor() ([]byte, []int) {
	return file_pkg_updater_updater_proto_rawDescGZIP(), []int{1, 1}
}

func (x *FilesUpdaterName_Response) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type FilesUpdaterVersion_Request struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FilesUpdaterVersion_Request) Reset() {
	*x = FilesUpdaterVersion_Request{}
	mi := &file_pkg_updater_updater_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FilesUpdaterVersion_Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FilesUpdaterVersion_Request) ProtoMessage() {}

func (x *FilesUpdaterVersion_Request) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_updater_updater_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FilesUpdaterVersion_Request.ProtoReflect.Descriptor instead.
func (*FilesUpdaterVersion_Request) Descriptor() ([]byte, []int) {
	return file_pkg_updater_updater_proto_rawDescGZIP(), []int{2, 0}
}

type FilesUpdaterVersion_Response struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Version       string                 `protobuf:"bytes,1,opt,name=version,proto3" json:"version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FilesUpdaterVersion_Response) Reset() {
	*x = FilesUpdaterVersion_Response{}
	mi := &file_pkg_updater_updater_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FilesUpdaterVersion_Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FilesUpdaterVersion_Response) ProtoMessage() {}

func (x *FilesUpdaterVersion_Response) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_updater_updater_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FilesUpdaterVersion_Response.ProtoReflect.Descriptor instead.
func (*FilesUpdaterVersion_Response) Descriptor() ([]byte, []int) {
	return file_pkg_updater_updater_proto_rawDescGZIP(), []int{2, 1}
}

func (x *FilesUpdaterVersion_Response) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

type FilesUpdaterForFiles_Request struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FilesUpdaterForFiles_Request) Reset() {
	*x = FilesUpdaterForFiles_Request{}
	mi := &file_pkg_updater_updater_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FilesUpdaterForFiles_Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FilesUpdaterForFiles_Request) ProtoMessage() {}

func (x *FilesUpdaterForFiles_Request) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_updater_updater_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FilesUpdaterForFiles_Request.ProtoReflect.Descriptor instead.
func (*FilesUpdaterForFiles_Request) Descriptor() ([]byte, []int) {
	return file_pkg_updater_updater_proto_rawDescGZIP(), []int{3, 0}
}

type FilesUpdaterForFiles_Response struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Files         string                 `protobuf:"bytes,1,opt,name=files,proto3" json:"files,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FilesUpdaterForFiles_Response) Reset() {
	*x = FilesUpdaterForFiles_Response{}
	mi := &file_pkg_updater_updater_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FilesUpdaterForFiles_Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FilesUpdaterForFiles_Response) ProtoMessage() {}

func (x *FilesUpdaterForFiles_Response) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_updater_updater_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FilesUpdaterForFiles_Response.ProtoReflect.Descriptor instead.
func (*FilesUpdaterForFiles_Response) Descriptor() ([]byte, []int) {
	return file_pkg_updater_updater_proto_rawDescGZIP(), []int{3, 1}
}

func (x *FilesUpdaterForFiles_Response) GetFiles() string {
	if x != nil {
		return x.Files
	}
	return ""
}

type FilesUpdaterApply_Request struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	File          string                 `protobuf:"bytes,1,opt,name=file,proto3" json:"file,omitempty"`
	NewVersion    string                 `protobuf:"bytes,2,opt,name=new_version,json=newVersion,proto3" json:"new_version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FilesUpdaterApply_Request) Reset() {
	*x = FilesUpdaterApply_Request{}
	mi := &file_pkg_updater_updater_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FilesUpdaterApply_Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FilesUpdaterApply_Request) ProtoMessage() {}

func (x *FilesUpdaterApply_Request) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_updater_updater_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FilesUpdaterApply_Request.ProtoReflect.Descriptor instead.
func (*FilesUpdaterApply_Request) Descriptor() ([]byte, []int) {
	return file_pkg_updater_updater_proto_rawDescGZIP(), []int{4, 0}
}

func (x *FilesUpdaterApply_Request) GetFile() string {
	if x != nil {
		return x.File
	}
	return ""
}

func (x *FilesUpdaterApply_Request) GetNewVersion() string {
	if x != nil {
		return x.NewVersion
	}
	return ""
}

type FilesUpdaterApply_Response struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Error         string                 `protobuf:"bytes,1,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FilesUpdaterApply_Response) Reset() {
	*x = FilesUpdaterApply_Response{}
	mi := &file_pkg_updater_updater_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FilesUpdaterApply_Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FilesUpdaterApply_Response) ProtoMessage() {}

func (x *FilesUpdaterApply_Response) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_updater_updater_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FilesUpdaterApply_Response.ProtoReflect.Descriptor instead.
func (*FilesUpdaterApply_Response) Descriptor() ([]byte, []int) {
	return file_pkg_updater_updater_proto_rawDescGZIP(), []int{4, 1}
}

func (x *FilesUpdaterApply_Response) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

var File_pkg_updater_updater_proto protoreflect.FileDescriptor

const file_pkg_updater_updater_proto_rawDesc = "" +
	"\n" +
	"\x19pkg/updater/updater.proto\"\xba\x01\n" +
	"\x10FilesUpdaterInit\x1a\x83\x01\n" +
	"\aRequest\x12=\n" +
	"\x06config\x18\x01 \x03(\v2%.FilesUpdaterInit.Request.ConfigEntryR\x06config\x1a9\n" +
	"\vConfigEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\x1a \n" +
	"\bResponse\x12\x14\n" +
	"\x05error\x18\x01 \x01(\tR\x05error\"=\n" +
	"\x10FilesUpdaterName\x1a\t\n" +
	"\aRequest\x1a\x1e\n" +
	"\bResponse\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\"F\n" +
	"\x13FilesUpdaterVersion\x1a\t\n" +
	"\aRequest\x1a$\n" +
	"\bResponse\x12\x18\n" +
	"\aversion\x18\x01 \x01(\tR\aversion\"C\n" +
	"\x14FilesUpdaterForFiles\x1a\t\n" +
	"\aRequest\x1a \n" +
	"\bResponse\x12\x14\n" +
	"\x05files\x18\x01 \x01(\tR\x05files\"u\n" +
	"\x11FilesUpdaterApply\x1a>\n" +
	"\aRequest\x12\x12\n" +
	"\x04file\x18\x01 \x01(\tR\x04file\x12\x1f\n" +
	"\vnew_version\x18\x02 \x01(\tR\n" +
	"newVersion\x1a \n" +
	"\bResponse\x12\x14\n" +
	"\x05error\x18\x01 \x01(\tR\x05error2\xe7\x02\n" +
	"\x12FilesUpdaterPlugin\x12=\n" +
	"\x04Init\x12\x19.FilesUpdaterInit.Request\x1a\x1a.FilesUpdaterInit.Response\x12=\n" +
	"\x04Name\x12\x19.FilesUpdaterName.Request\x1a\x1a.FilesUpdaterName.Response\x12F\n" +
	"\aVersion\x12\x1c.FilesUpdaterVersion.Request\x1a\x1d.FilesUpdaterVersion.Response\x12I\n" +
	"\bForFiles\x12\x1d.FilesUpdaterForFiles.Request\x1a\x1e.FilesUpdaterForFiles.Response\x12@\n" +
	"\x05Apply\x12\x1a.FilesUpdaterApply.Request\x1a\x1b.FilesUpdaterApply.ResponseB@Z>github.com/go-semantic-release/semantic-release/v2/pkg/updaterb\x06proto3"

var (
	file_pkg_updater_updater_proto_rawDescOnce sync.Once
	file_pkg_updater_updater_proto_rawDescData []byte
)

func file_pkg_updater_updater_proto_rawDescGZIP() []byte {
	file_pkg_updater_updater_proto_rawDescOnce.Do(func() {
		file_pkg_updater_updater_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pkg_updater_updater_proto_rawDesc), len(file_pkg_updater_updater_proto_rawDesc)))
	})
	return file_pkg_updater_updater_proto_rawDescData
}

var file_pkg_updater_updater_proto_msgTypes = make([]protoimpl.MessageInfo, 16)
var file_pkg_updater_updater_proto_goTypes = []any{
	(*FilesUpdaterInit)(nil),              // 0: FilesUpdaterInit
	(*FilesUpdaterName)(nil),              // 1: FilesUpdaterName
	(*FilesUpdaterVersion)(nil),           // 2: FilesUpdaterVersion
	(*FilesUpdaterForFiles)(nil),          // 3: FilesUpdaterForFiles
	(*FilesUpdaterApply)(nil),             // 4: FilesUpdaterApply
	(*FilesUpdaterInit_Request)(nil),      // 5: FilesUpdaterInit.Request
	(*FilesUpdaterInit_Response)(nil),     // 6: FilesUpdaterInit.Response
	nil,                                   // 7: FilesUpdaterInit.Request.ConfigEntry
	(*FilesUpdaterName_Request)(nil),      // 8: FilesUpdaterName.Request
	(*FilesUpdaterName_Response)(nil),     // 9: FilesUpdaterName.Response
	(*FilesUpdaterVersion_Request)(nil),   // 10: FilesUpdaterVersion.Request
	(*FilesUpdaterVersion_Response)(nil),  // 11: FilesUpdaterVersion.Response
	(*FilesUpdaterForFiles_Request)(nil),  // 12: FilesUpdaterForFiles.Request
	(*FilesUpdaterForFiles_Response)(nil), // 13: FilesUpdaterForFiles.Response
	(*FilesUpdaterApply_Request)(nil),     // 14: FilesUpdaterApply.Request
	(*FilesUpdaterApply_Response)(nil),    // 15: FilesUpdaterApply.Response
}
var file_pkg_updater_updater_proto_depIdxs = []int32{
	7,  // 0: FilesUpdaterInit.Request.config:type_name -> FilesUpdaterInit.Request.ConfigEntry
	5,  // 1: FilesUpdaterPlugin.Init:input_type -> FilesUpdaterInit.Request
	8,  // 2: FilesUpdaterPlugin.Name:input_type -> FilesUpdaterName.Request
	10, // 3: FilesUpdaterPlugin.Version:input_type -> FilesUpdaterVersion.Request
	12, // 4: FilesUpdaterPlugin.ForFiles:input_type -> FilesUpdaterForFiles.Request
	14, // 5: FilesUpdaterPlugin.Apply:input_type -> FilesUpdaterApply.Request
	6,  // 6: FilesUpdaterPlugin.Init:output_type -> FilesUpdaterInit.Response
	9,  // 7: FilesUpdaterPlugin.Name:output_type -> FilesUpdaterName.Response
	11, // 8: FilesUpdaterPlugin.Version:output_type -> FilesUpdaterVersion.Response
	13, // 9: FilesUpdaterPlugin.ForFiles:output_type -> FilesUpdaterForFiles.Response
	15, // 10: FilesUpdaterPlugin.Apply:output_type -> FilesUpdaterApply.Response
	6,  // [6:11] is the sub-list for method output_type
	1,  // [1:6] is the sub-list for method input_type
	1,  // [1:1] is the sub-list for extension type_name
	1,  // [1:1] is the sub-list for extension extendee
	0,  // [0:1] is the sub-list for field type_name
}

func init() { file_pkg_updater_updater_proto_init() }
func file_pkg_updater_updater_proto_init() {
	if File_pkg_updater_updater_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pkg_updater_updater_proto_rawDesc), len(file_pkg_updater_updater_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   16,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pkg_updater_updater_proto_goTypes,
		DependencyIndexes: file_pkg_updater_updater_proto_depIdxs,
		MessageInfos:      file_pkg_updater_updater_proto_msgTypes,
	}.Build()
	File_pkg_updater_updater_proto = out.File
	file_pkg_updater_updater_proto_goTypes = nil
	file_pkg_updater_updater_proto_depIdxs = nil
}
