// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.1
// source: pkg/analyzer/commit_analyzer.proto

package analyzer

import (
	semrel "github.com/go-semantic-release/semantic-release/v2/pkg/semrel"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CommitAnalyzerInit struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CommitAnalyzerInit) Reset() {
	*x = CommitAnalyzerInit{}
	mi := &file_pkg_analyzer_commit_analyzer_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CommitAnalyzerInit) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommitAnalyzerInit) ProtoMessage() {}

func (x *CommitAnalyzerInit) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_analyzer_commit_analyzer_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommitAnalyzerInit.ProtoReflect.Descriptor instead.
func (*CommitAnalyzerInit) Descriptor() ([]byte, []int) {
	return file_pkg_analyzer_commit_analyzer_proto_rawDescGZIP(), []int{0}
}

type CommitAnalyzerName struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CommitAnalyzerName) Reset() {
	*x = CommitAnalyzerName{}
	mi := &file_pkg_analyzer_commit_analyzer_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CommitAnalyzerName) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommitAnalyzerName) ProtoMessage() {}

func (x *CommitAnalyzerName) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_analyzer_commit_analyzer_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommitAnalyzerName.ProtoReflect.Descriptor instead.
func (*CommitAnalyzerName) Descriptor() ([]byte, []int) {
	return file_pkg_analyzer_commit_analyzer_proto_rawDescGZIP(), []int{1}
}

type CommitAnalyzerVersion struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CommitAnalyzerVersion) Reset() {
	*x = CommitAnalyzerVersion{}
	mi := &file_pkg_analyzer_commit_analyzer_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CommitAnalyzerVersion) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommitAnalyzerVersion) ProtoMessage() {}

func (x *CommitAnalyzerVersion) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_analyzer_commit_analyzer_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommitAnalyzerVersion.ProtoReflect.Descriptor instead.
func (*CommitAnalyzerVersion) Descriptor() ([]byte, []int) {
	return file_pkg_analyzer_commit_analyzer_proto_rawDescGZIP(), []int{2}
}

type AnalyzeCommits struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AnalyzeCommits) Reset() {
	*x = AnalyzeCommits{}
	mi := &file_pkg_analyzer_commit_analyzer_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AnalyzeCommits) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AnalyzeCommits) ProtoMessage() {}

func (x *AnalyzeCommits) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_analyzer_commit_analyzer_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AnalyzeCommits.ProtoReflect.Descriptor instead.
func (*AnalyzeCommits) Descriptor() ([]byte, []int) {
	return file_pkg_analyzer_commit_analyzer_proto_rawDescGZIP(), []int{3}
}

type CommitAnalyzerInit_Request struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Config        map[string]string      `protobuf:"bytes,1,rep,name=config,proto3" json:"config,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CommitAnalyzerInit_Request) Reset() {
	*x = CommitAnalyzerInit_Request{}
	mi := &file_pkg_analyzer_commit_analyzer_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CommitAnalyzerInit_Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommitAnalyzerInit_Request) ProtoMessage() {}

func (x *CommitAnalyzerInit_Request) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_analyzer_commit_analyzer_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommitAnalyzerInit_Request.ProtoReflect.Descriptor instead.
func (*CommitAnalyzerInit_Request) Descriptor() ([]byte, []int) {
	return file_pkg_analyzer_commit_analyzer_proto_rawDescGZIP(), []int{0, 0}
}

func (x *CommitAnalyzerInit_Request) GetConfig() map[string]string {
	if x != nil {
		return x.Config
	}
	return nil
}

type CommitAnalyzerInit_Response struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Error         string                 `protobuf:"bytes,1,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CommitAnalyzerInit_Response) Reset() {
	*x = CommitAnalyzerInit_Response{}
	mi := &file_pkg_analyzer_commit_analyzer_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CommitAnalyzerInit_Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommitAnalyzerInit_Response) ProtoMessage() {}

func (x *CommitAnalyzerInit_Response) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_analyzer_commit_analyzer_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommitAnalyzerInit_Response.ProtoReflect.Descriptor instead.
func (*CommitAnalyzerInit_Response) Descriptor() ([]byte, []int) {
	return file_pkg_analyzer_commit_analyzer_proto_rawDescGZIP(), []int{0, 1}
}

func (x *CommitAnalyzerInit_Response) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type CommitAnalyzerName_Request struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CommitAnalyzerName_Request) Reset() {
	*x = CommitAnalyzerName_Request{}
	mi := &file_pkg_analyzer_commit_analyzer_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CommitAnalyzerName_Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommitAnalyzerName_Request) ProtoMessage() {}

func (x *CommitAnalyzerName_Request) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_analyzer_commit_analyzer_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommitAnalyzerName_Request.ProtoReflect.Descriptor instead.
func (*CommitAnalyzerName_Request) Descriptor() ([]byte, []int) {
	return file_pkg_analyzer_commit_analyzer_proto_rawDescGZIP(), []int{1, 0}
}

type CommitAnalyzerName_Response struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CommitAnalyzerName_Response) Reset() {
	*x = CommitAnalyzerName_Response{}
	mi := &file_pkg_analyzer_commit_analyzer_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CommitAnalyzerName_Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommitAnalyzerName_Response) ProtoMessage() {}

func (x *CommitAnalyzerName_Response) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_analyzer_commit_analyzer_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommitAnalyzerName_Response.ProtoReflect.Descriptor instead.
func (*CommitAnalyzerName_Response) Descriptor() ([]byte, []int) {
	return file_pkg_analyzer_commit_analyzer_proto_rawDescGZIP(), []int{1, 1}
}

func (x *CommitAnalyzerName_Response) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type CommitAnalyzerVersion_Request struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CommitAnalyzerVersion_Request) Reset() {
	*x = CommitAnalyzerVersion_Request{}
	mi := &file_pkg_analyzer_commit_analyzer_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CommitAnalyzerVersion_Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommitAnalyzerVersion_Request) ProtoMessage() {}

func (x *CommitAnalyzerVersion_Request) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_analyzer_commit_analyzer_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommitAnalyzerVersion_Request.ProtoReflect.Descriptor instead.
func (*CommitAnalyzerVersion_Request) Descriptor() ([]byte, []int) {
	return file_pkg_analyzer_commit_analyzer_proto_rawDescGZIP(), []int{2, 0}
}

type CommitAnalyzerVersion_Response struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Version       string                 `protobuf:"bytes,1,opt,name=version,proto3" json:"version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CommitAnalyzerVersion_Response) Reset() {
	*x = CommitAnalyzerVersion_Response{}
	mi := &file_pkg_analyzer_commit_analyzer_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CommitAnalyzerVersion_Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommitAnalyzerVersion_Response) ProtoMessage() {}

func (x *CommitAnalyzerVersion_Response) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_analyzer_commit_analyzer_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommitAnalyzerVersion_Response.ProtoReflect.Descriptor instead.
func (*CommitAnalyzerVersion_Response) Descriptor() ([]byte, []int) {
	return file_pkg_analyzer_commit_analyzer_proto_rawDescGZIP(), []int{2, 1}
}

func (x *CommitAnalyzerVersion_Response) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

type AnalyzeCommits_Request struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RawCommits    []*semrel.RawCommit    `protobuf:"bytes,1,rep,name=raw_commits,json=rawCommits,proto3" json:"raw_commits,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AnalyzeCommits_Request) Reset() {
	*x = AnalyzeCommits_Request{}
	mi := &file_pkg_analyzer_commit_analyzer_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AnalyzeCommits_Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AnalyzeCommits_Request) ProtoMessage() {}

func (x *AnalyzeCommits_Request) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_analyzer_commit_analyzer_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AnalyzeCommits_Request.ProtoReflect.Descriptor instead.
func (*AnalyzeCommits_Request) Descriptor() ([]byte, []int) {
	return file_pkg_analyzer_commit_analyzer_proto_rawDescGZIP(), []int{3, 0}
}

func (x *AnalyzeCommits_Request) GetRawCommits() []*semrel.RawCommit {
	if x != nil {
		return x.RawCommits
	}
	return nil
}

type AnalyzeCommits_Response struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Commits       []*semrel.Commit       `protobuf:"bytes,1,rep,name=commits,proto3" json:"commits,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AnalyzeCommits_Response) Reset() {
	*x = AnalyzeCommits_Response{}
	mi := &file_pkg_analyzer_commit_analyzer_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AnalyzeCommits_Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AnalyzeCommits_Response) ProtoMessage() {}

func (x *AnalyzeCommits_Response) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_analyzer_commit_analyzer_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AnalyzeCommits_Response.ProtoReflect.Descriptor instead.
func (*AnalyzeCommits_Response) Descriptor() ([]byte, []int) {
	return file_pkg_analyzer_commit_analyzer_proto_rawDescGZIP(), []int{3, 1}
}

func (x *AnalyzeCommits_Response) GetCommits() []*semrel.Commit {
	if x != nil {
		return x.Commits
	}
	return nil
}

var File_pkg_analyzer_commit_analyzer_proto protoreflect.FileDescriptor

const file_pkg_analyzer_commit_analyzer_proto_rawDesc = "" +
	"\n" +
	"\"pkg/analyzer/commit_analyzer.proto\x1a\x18pkg/semrel/structs.proto\"\xbe\x01\n" +
	"\x12CommitAnalyzerInit\x1a\x85\x01\n" +
	"\aRequest\x12?\n" +
	"\x06config\x18\x01 \x03(\v2'.CommitAnalyzerInit.Request.ConfigEntryR\x06config\x1a9\n" +
	"\vConfigEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\x1a \n" +
	"\bResponse\x12\x14\n" +
	"\x05error\x18\x01 \x01(\tR\x05error\"?\n" +
	"\x12CommitAnalyzerName\x1a\t\n" +
	"\aRequest\x1a\x1e\n" +
	"\bResponse\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\"H\n" +
	"\x15CommitAnalyzerVersion\x1a\t\n" +
	"\aRequest\x1a$\n" +
	"\bResponse\x12\x18\n" +
	"\aversion\x18\x01 \x01(\tR\aversion\"w\n" +
	"\x0eAnalyzeCommits\x1a6\n" +
	"\aRequest\x12+\n" +
	"\vraw_commits\x18\x01 \x03(\v2\n" +
	".RawCommitR\n" +
	"rawCommits\x1a-\n" +
	"\bResponse\x12!\n" +
	"\acommits\x18\x01 \x03(\v2\a.CommitR\acommits2\xa6\x02\n" +
	"\x14CommitAnalyzerPlugin\x12A\n" +
	"\x04Init\x12\x1b.CommitAnalyzerInit.Request\x1a\x1c.CommitAnalyzerInit.Response\x12A\n" +
	"\x04Name\x12\x1b.CommitAnalyzerName.Request\x1a\x1c.CommitAnalyzerName.Response\x12J\n" +
	"\aVersion\x12\x1e.CommitAnalyzerVersion.Request\x1a\x1f.CommitAnalyzerVersion.Response\x12<\n" +
	"\aAnalyze\x12\x17.AnalyzeCommits.Request\x1a\x18.AnalyzeCommits.ResponseBAZ?github.com/go-semantic-release/semantic-release/v2/pkg/analyzerb\x06proto3"

var (
	file_pkg_analyzer_commit_analyzer_proto_rawDescOnce sync.Once
	file_pkg_analyzer_commit_analyzer_proto_rawDescData []byte
)

func file_pkg_analyzer_commit_analyzer_proto_rawDescGZIP() []byte {
	file_pkg_analyzer_commit_analyzer_proto_rawDescOnce.Do(func() {
		file_pkg_analyzer_commit_analyzer_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pkg_analyzer_commit_analyzer_proto_rawDesc), len(file_pkg_analyzer_commit_analyzer_proto_rawDesc)))
	})
	return file_pkg_analyzer_commit_analyzer_proto_rawDescData
}

var file_pkg_analyzer_commit_analyzer_proto_msgTypes = make([]protoimpl.MessageInfo, 13)
var file_pkg_analyzer_commit_analyzer_proto_goTypes = []any{
	(*CommitAnalyzerInit)(nil),             // 0: CommitAnalyzerInit
	(*CommitAnalyzerName)(nil),             // 1: CommitAnalyzerName
	(*CommitAnalyzerVersion)(nil),          // 2: CommitAnalyzerVersion
	(*AnalyzeCommits)(nil),                 // 3: AnalyzeCommits
	(*CommitAnalyzerInit_Request)(nil),     // 4: CommitAnalyzerInit.Request
	(*CommitAnalyzerInit_Response)(nil),    // 5: CommitAnalyzerInit.Response
	nil,                                    // 6: CommitAnalyzerInit.Request.ConfigEntry
	(*CommitAnalyzerName_Request)(nil),     // 7: CommitAnalyzerName.Request
	(*CommitAnalyzerName_Response)(nil),    // 8: CommitAnalyzerName.Response
	(*CommitAnalyzerVersion_Request)(nil),  // 9: CommitAnalyzerVersion.Request
	(*CommitAnalyzerVersion_Response)(nil), // 10: CommitAnalyzerVersion.Response
	(*AnalyzeCommits_Request)(nil),         // 11: AnalyzeCommits.Request
	(*AnalyzeCommits_Response)(nil),        // 12: AnalyzeCommits.Response
	(*semrel.RawCommit)(nil),               // 13: RawCommit
	(*semrel.Commit)(nil),                  // 14: Commit
}
var file_pkg_analyzer_commit_analyzer_proto_depIdxs = []int32{
	6,  // 0: CommitAnalyzerInit.Request.config:type_name -> CommitAnalyzerInit.Request.ConfigEntry
	13, // 1: AnalyzeCommits.Request.raw_commits:type_name -> RawCommit
	14, // 2: AnalyzeCommits.Response.commits:type_name -> Commit
	4,  // 3: CommitAnalyzerPlugin.Init:input_type -> CommitAnalyzerInit.Request
	7,  // 4: CommitAnalyzerPlugin.Name:input_type -> CommitAnalyzerName.Request
	9,  // 5: CommitAnalyzerPlugin.Version:input_type -> CommitAnalyzerVersion.Request
	11, // 6: CommitAnalyzerPlugin.Analyze:input_type -> AnalyzeCommits.Request
	5,  // 7: CommitAnalyzerPlugin.Init:output_type -> CommitAnalyzerInit.Response
	8,  // 8: CommitAnalyzerPlugin.Name:output_type -> CommitAnalyzerName.Response
	10, // 9: CommitAnalyzerPlugin.Version:output_type -> CommitAnalyzerVersion.Response
	12, // 10: CommitAnalyzerPlugin.Analyze:output_type -> AnalyzeCommits.Response
	7,  // [7:11] is the sub-list for method output_type
	3,  // [3:7] is the sub-list for method input_type
	3,  // [3:3] is the sub-list for extension type_name
	3,  // [3:3] is the sub-list for extension extendee
	0,  // [0:3] is the sub-list for field type_name
}

func init() { file_pkg_analyzer_commit_analyzer_proto_init() }
func file_pkg_analyzer_commit_analyzer_proto_init() {
	if File_pkg_analyzer_commit_analyzer_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pkg_analyzer_commit_analyzer_proto_rawDesc), len(file_pkg_analyzer_commit_analyzer_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   13,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pkg_analyzer_commit_analyzer_proto_goTypes,
		DependencyIndexes: file_pkg_analyzer_commit_analyzer_proto_depIdxs,
		MessageInfos:      file_pkg_analyzer_commit_analyzer_proto_msgTypes,
	}.Build()
	File_pkg_analyzer_commit_analyzer_proto = out.File
	file_pkg_analyzer_commit_analyzer_proto_goTypes = nil
	file_pkg_analyzer_commit_analyzer_proto_depIdxs = nil
}
