// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.1
// source: pkg/hooks/hooks.proto

package hooks

import (
	provider "github.com/go-semantic-release/semantic-release/v2/pkg/provider"
	semrel "github.com/go-semantic-release/semantic-release/v2/pkg/semrel"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type NoReleaseReason int32

const (
	NoReleaseReason_CONDITION NoReleaseReason = 0
	NoReleaseReason_NO_CHANGE NoReleaseReason = 1
)

// Enum value maps for NoReleaseReason.
var (
	NoReleaseReason_name = map[int32]string{
		0: "CONDITION",
		1: "NO_CHANGE",
	}
	NoReleaseReason_value = map[string]int32{
		"CONDITION": 0,
		"NO_CHANGE": 1,
	}
)

func (x NoReleaseReason) Enum() *NoReleaseReason {
	p := new(NoReleaseReason)
	*p = x
	return p
}

func (x NoReleaseReason) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (NoReleaseReason) Descriptor() protoreflect.EnumDescriptor {
	return file_pkg_hooks_hooks_proto_enumTypes[0].Descriptor()
}

func (NoReleaseReason) Type() protoreflect.EnumType {
	return &file_pkg_hooks_hooks_proto_enumTypes[0]
}

func (x NoReleaseReason) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use NoReleaseReason.Descriptor instead.
func (NoReleaseReason) EnumDescriptor() ([]byte, []int) {
	return file_pkg_hooks_hooks_proto_rawDescGZIP(), []int{0}
}

type HooksInit struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HooksInit) Reset() {
	*x = HooksInit{}
	mi := &file_pkg_hooks_hooks_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HooksInit) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HooksInit) ProtoMessage() {}

func (x *HooksInit) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_hooks_hooks_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HooksInit.ProtoReflect.Descriptor instead.
func (*HooksInit) Descriptor() ([]byte, []int) {
	return file_pkg_hooks_hooks_proto_rawDescGZIP(), []int{0}
}

type HooksName struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HooksName) Reset() {
	*x = HooksName{}
	mi := &file_pkg_hooks_hooks_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HooksName) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HooksName) ProtoMessage() {}

func (x *HooksName) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_hooks_hooks_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HooksName.ProtoReflect.Descriptor instead.
func (*HooksName) Descriptor() ([]byte, []int) {
	return file_pkg_hooks_hooks_proto_rawDescGZIP(), []int{1}
}

type HooksVersion struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HooksVersion) Reset() {
	*x = HooksVersion{}
	mi := &file_pkg_hooks_hooks_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HooksVersion) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HooksVersion) ProtoMessage() {}

func (x *HooksVersion) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_hooks_hooks_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HooksVersion.ProtoReflect.Descriptor instead.
func (*HooksVersion) Descriptor() ([]byte, []int) {
	return file_pkg_hooks_hooks_proto_rawDescGZIP(), []int{2}
}

type SuccessHookConfig struct {
	state         protoimpl.MessageState   `protogen:"open.v1"`
	Commits       []*semrel.Commit         `protobuf:"bytes,1,rep,name=commits,proto3" json:"commits,omitempty"`
	PrevRelease   *semrel.Release          `protobuf:"bytes,2,opt,name=prev_release,json=prevRelease,proto3" json:"prev_release,omitempty"`
	NewRelease    *semrel.Release          `protobuf:"bytes,3,opt,name=new_release,json=newRelease,proto3" json:"new_release,omitempty"`
	Changelog     string                   `protobuf:"bytes,4,opt,name=changelog,proto3" json:"changelog,omitempty"`
	RepoInfo      *provider.RepositoryInfo `protobuf:"bytes,5,opt,name=repo_info,json=repoInfo,proto3" json:"repo_info,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SuccessHookConfig) Reset() {
	*x = SuccessHookConfig{}
	mi := &file_pkg_hooks_hooks_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SuccessHookConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SuccessHookConfig) ProtoMessage() {}

func (x *SuccessHookConfig) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_hooks_hooks_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SuccessHookConfig.ProtoReflect.Descriptor instead.
func (*SuccessHookConfig) Descriptor() ([]byte, []int) {
	return file_pkg_hooks_hooks_proto_rawDescGZIP(), []int{3}
}

func (x *SuccessHookConfig) GetCommits() []*semrel.Commit {
	if x != nil {
		return x.Commits
	}
	return nil
}

func (x *SuccessHookConfig) GetPrevRelease() *semrel.Release {
	if x != nil {
		return x.PrevRelease
	}
	return nil
}

func (x *SuccessHookConfig) GetNewRelease() *semrel.Release {
	if x != nil {
		return x.NewRelease
	}
	return nil
}

func (x *SuccessHookConfig) GetChangelog() string {
	if x != nil {
		return x.Changelog
	}
	return ""
}

func (x *SuccessHookConfig) GetRepoInfo() *provider.RepositoryInfo {
	if x != nil {
		return x.RepoInfo
	}
	return nil
}

type SuccessHook struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SuccessHook) Reset() {
	*x = SuccessHook{}
	mi := &file_pkg_hooks_hooks_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SuccessHook) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SuccessHook) ProtoMessage() {}

func (x *SuccessHook) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_hooks_hooks_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SuccessHook.ProtoReflect.Descriptor instead.
func (*SuccessHook) Descriptor() ([]byte, []int) {
	return file_pkg_hooks_hooks_proto_rawDescGZIP(), []int{4}
}

type NoReleaseConfig struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Reason        NoReleaseReason        `protobuf:"varint,1,opt,name=reason,proto3,enum=NoReleaseReason" json:"reason,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NoReleaseConfig) Reset() {
	*x = NoReleaseConfig{}
	mi := &file_pkg_hooks_hooks_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NoReleaseConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NoReleaseConfig) ProtoMessage() {}

func (x *NoReleaseConfig) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_hooks_hooks_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NoReleaseConfig.ProtoReflect.Descriptor instead.
func (*NoReleaseConfig) Descriptor() ([]byte, []int) {
	return file_pkg_hooks_hooks_proto_rawDescGZIP(), []int{5}
}

func (x *NoReleaseConfig) GetReason() NoReleaseReason {
	if x != nil {
		return x.Reason
	}
	return NoReleaseReason_CONDITION
}

func (x *NoReleaseConfig) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type NoReleaseHook struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NoReleaseHook) Reset() {
	*x = NoReleaseHook{}
	mi := &file_pkg_hooks_hooks_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NoReleaseHook) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NoReleaseHook) ProtoMessage() {}

func (x *NoReleaseHook) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_hooks_hooks_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NoReleaseHook.ProtoReflect.Descriptor instead.
func (*NoReleaseHook) Descriptor() ([]byte, []int) {
	return file_pkg_hooks_hooks_proto_rawDescGZIP(), []int{6}
}

type HooksInit_Request struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Config        map[string]string      `protobuf:"bytes,1,rep,name=config,proto3" json:"config,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HooksInit_Request) Reset() {
	*x = HooksInit_Request{}
	mi := &file_pkg_hooks_hooks_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HooksInit_Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HooksInit_Request) ProtoMessage() {}

func (x *HooksInit_Request) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_hooks_hooks_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HooksInit_Request.ProtoReflect.Descriptor instead.
func (*HooksInit_Request) Descriptor() ([]byte, []int) {
	return file_pkg_hooks_hooks_proto_rawDescGZIP(), []int{0, 0}
}

func (x *HooksInit_Request) GetConfig() map[string]string {
	if x != nil {
		return x.Config
	}
	return nil
}

type HooksInit_Response struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Error         string                 `protobuf:"bytes,1,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HooksInit_Response) Reset() {
	*x = HooksInit_Response{}
	mi := &file_pkg_hooks_hooks_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HooksInit_Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HooksInit_Response) ProtoMessage() {}

func (x *HooksInit_Response) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_hooks_hooks_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HooksInit_Response.ProtoReflect.Descriptor instead.
func (*HooksInit_Response) Descriptor() ([]byte, []int) {
	return file_pkg_hooks_hooks_proto_rawDescGZIP(), []int{0, 1}
}

func (x *HooksInit_Response) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type HooksName_Request struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HooksName_Request) Reset() {
	*x = HooksName_Request{}
	mi := &file_pkg_hooks_hooks_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HooksName_Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HooksName_Request) ProtoMessage() {}

func (x *HooksName_Request) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_hooks_hooks_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HooksName_Request.ProtoReflect.Descriptor instead.
func (*HooksName_Request) Descriptor() ([]byte, []int) {
	return file_pkg_hooks_hooks_proto_rawDescGZIP(), []int{1, 0}
}

type HooksName_Response struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HooksName_Response) Reset() {
	*x = HooksName_Response{}
	mi := &file_pkg_hooks_hooks_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HooksName_Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HooksName_Response) ProtoMessage() {}

func (x *HooksName_Response) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_hooks_hooks_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HooksName_Response.ProtoReflect.Descriptor instead.
func (*HooksName_Response) Descriptor() ([]byte, []int) {
	return file_pkg_hooks_hooks_proto_rawDescGZIP(), []int{1, 1}
}

func (x *HooksName_Response) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type HooksVersion_Request struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HooksVersion_Request) Reset() {
	*x = HooksVersion_Request{}
	mi := &file_pkg_hooks_hooks_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HooksVersion_Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HooksVersion_Request) ProtoMessage() {}

func (x *HooksVersion_Request) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_hooks_hooks_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HooksVersion_Request.ProtoReflect.Descriptor instead.
func (*HooksVersion_Request) Descriptor() ([]byte, []int) {
	return file_pkg_hooks_hooks_proto_rawDescGZIP(), []int{2, 0}
}

type HooksVersion_Response struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Version       string                 `protobuf:"bytes,1,opt,name=version,proto3" json:"version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HooksVersion_Response) Reset() {
	*x = HooksVersion_Response{}
	mi := &file_pkg_hooks_hooks_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HooksVersion_Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HooksVersion_Response) ProtoMessage() {}

func (x *HooksVersion_Response) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_hooks_hooks_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HooksVersion_Response.ProtoReflect.Descriptor instead.
func (*HooksVersion_Response) Descriptor() ([]byte, []int) {
	return file_pkg_hooks_hooks_proto_rawDescGZIP(), []int{2, 1}
}

func (x *HooksVersion_Response) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

type SuccessHook_Request struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Config        *SuccessHookConfig     `protobuf:"bytes,1,opt,name=config,proto3" json:"config,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SuccessHook_Request) Reset() {
	*x = SuccessHook_Request{}
	mi := &file_pkg_hooks_hooks_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SuccessHook_Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SuccessHook_Request) ProtoMessage() {}

func (x *SuccessHook_Request) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_hooks_hooks_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SuccessHook_Request.ProtoReflect.Descriptor instead.
func (*SuccessHook_Request) Descriptor() ([]byte, []int) {
	return file_pkg_hooks_hooks_proto_rawDescGZIP(), []int{4, 0}
}

func (x *SuccessHook_Request) GetConfig() *SuccessHookConfig {
	if x != nil {
		return x.Config
	}
	return nil
}

type SuccessHook_Response struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Error         string                 `protobuf:"bytes,1,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SuccessHook_Response) Reset() {
	*x = SuccessHook_Response{}
	mi := &file_pkg_hooks_hooks_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SuccessHook_Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SuccessHook_Response) ProtoMessage() {}

func (x *SuccessHook_Response) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_hooks_hooks_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SuccessHook_Response.ProtoReflect.Descriptor instead.
func (*SuccessHook_Response) Descriptor() ([]byte, []int) {
	return file_pkg_hooks_hooks_proto_rawDescGZIP(), []int{4, 1}
}

func (x *SuccessHook_Response) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type NoReleaseHook_Request struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Config        *NoReleaseConfig       `protobuf:"bytes,1,opt,name=config,proto3" json:"config,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NoReleaseHook_Request) Reset() {
	*x = NoReleaseHook_Request{}
	mi := &file_pkg_hooks_hooks_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NoReleaseHook_Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NoReleaseHook_Request) ProtoMessage() {}

func (x *NoReleaseHook_Request) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_hooks_hooks_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NoReleaseHook_Request.ProtoReflect.Descriptor instead.
func (*NoReleaseHook_Request) Descriptor() ([]byte, []int) {
	return file_pkg_hooks_hooks_proto_rawDescGZIP(), []int{6, 0}
}

func (x *NoReleaseHook_Request) GetConfig() *NoReleaseConfig {
	if x != nil {
		return x.Config
	}
	return nil
}

type NoReleaseHook_Response struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Error         string                 `protobuf:"bytes,1,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NoReleaseHook_Response) Reset() {
	*x = NoReleaseHook_Response{}
	mi := &file_pkg_hooks_hooks_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NoReleaseHook_Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NoReleaseHook_Response) ProtoMessage() {}

func (x *NoReleaseHook_Response) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_hooks_hooks_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NoReleaseHook_Response.ProtoReflect.Descriptor instead.
func (*NoReleaseHook_Response) Descriptor() ([]byte, []int) {
	return file_pkg_hooks_hooks_proto_rawDescGZIP(), []int{6, 1}
}

func (x *NoReleaseHook_Response) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

var File_pkg_hooks_hooks_proto protoreflect.FileDescriptor

const file_pkg_hooks_hooks_proto_rawDesc = "" +
	"\n" +
	"\x15pkg/hooks/hooks.proto\x1a\x18pkg/semrel/structs.proto\x1a\x1bpkg/provider/provider.proto\"\xab\x01\n" +
	"\tHooksInit\x1a|\n" +
	"\aRequest\x126\n" +
	"\x06config\x18\x01 \x03(\v2\x1e.HooksInit.Request.ConfigEntryR\x06config\x1a9\n" +
	"\vConfigEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\x1a \n" +
	"\bResponse\x12\x14\n" +
	"\x05error\x18\x01 \x01(\tR\x05error\"6\n" +
	"\tHooksName\x1a\t\n" +
	"\aRequest\x1a\x1e\n" +
	"\bResponse\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\"?\n" +
	"\fHooksVersion\x1a\t\n" +
	"\aRequest\x1a$\n" +
	"\bResponse\x12\x18\n" +
	"\aversion\x18\x01 \x01(\tR\aversion\"\xda\x01\n" +
	"\x11SuccessHookConfig\x12!\n" +
	"\acommits\x18\x01 \x03(\v2\a.CommitR\acommits\x12+\n" +
	"\fprev_release\x18\x02 \x01(\v2\b.ReleaseR\vprevRelease\x12)\n" +
	"\vnew_release\x18\x03 \x01(\v2\b.ReleaseR\n" +
	"newRelease\x12\x1c\n" +
	"\tchangelog\x18\x04 \x01(\tR\tchangelog\x12,\n" +
	"\trepo_info\x18\x05 \x01(\v2\x0f.RepositoryInfoR\brepoInfo\"f\n" +
	"\vSuccessHook\x1a5\n" +
	"\aRequest\x12*\n" +
	"\x06config\x18\x01 \x01(\v2\x12.SuccessHookConfigR\x06config\x1a \n" +
	"\bResponse\x12\x14\n" +
	"\x05error\x18\x01 \x01(\tR\x05error\"U\n" +
	"\x0fNoReleaseConfig\x12(\n" +
	"\x06reason\x18\x01 \x01(\x0e2\x10.NoReleaseReasonR\x06reason\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"f\n" +
	"\rNoReleaseHook\x1a3\n" +
	"\aRequest\x12(\n" +
	"\x06config\x18\x01 \x01(\v2\x10.NoReleaseConfigR\x06config\x1a \n" +
	"\bResponse\x12\x14\n" +
	"\x05error\x18\x01 \x01(\tR\x05error*/\n" +
	"\x0fNoReleaseReason\x12\r\n" +
	"\tCONDITION\x10\x00\x12\r\n" +
	"\tNO_CHANGE\x10\x012\x9f\x02\n" +
	"\vHooksPlugin\x12/\n" +
	"\x04Init\x12\x12.HooksInit.Request\x1a\x13.HooksInit.Response\x12/\n" +
	"\x04Name\x12\x12.HooksName.Request\x1a\x13.HooksName.Response\x128\n" +
	"\aVersion\x12\x15.HooksVersion.Request\x1a\x16.HooksVersion.Response\x126\n" +
	"\aSuccess\x12\x14.SuccessHook.Request\x1a\x15.SuccessHook.Response\x12<\n" +
	"\tNoRelease\x12\x16.NoReleaseHook.Request\x1a\x17.NoReleaseHook.ResponseB>Z<github.com/go-semantic-release/semantic-release/v2/pkg/hooksb\x06proto3"

var (
	file_pkg_hooks_hooks_proto_rawDescOnce sync.Once
	file_pkg_hooks_hooks_proto_rawDescData []byte
)

func file_pkg_hooks_hooks_proto_rawDescGZIP() []byte {
	file_pkg_hooks_hooks_proto_rawDescOnce.Do(func() {
		file_pkg_hooks_hooks_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pkg_hooks_hooks_proto_rawDesc), len(file_pkg_hooks_hooks_proto_rawDesc)))
	})
	return file_pkg_hooks_hooks_proto_rawDescData
}

var file_pkg_hooks_hooks_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_pkg_hooks_hooks_proto_msgTypes = make([]protoimpl.MessageInfo, 18)
var file_pkg_hooks_hooks_proto_goTypes = []any{
	(NoReleaseReason)(0),            // 0: NoReleaseReason
	(*HooksInit)(nil),               // 1: HooksInit
	(*HooksName)(nil),               // 2: HooksName
	(*HooksVersion)(nil),            // 3: HooksVersion
	(*SuccessHookConfig)(nil),       // 4: SuccessHookConfig
	(*SuccessHook)(nil),             // 5: SuccessHook
	(*NoReleaseConfig)(nil),         // 6: NoReleaseConfig
	(*NoReleaseHook)(nil),           // 7: NoReleaseHook
	(*HooksInit_Request)(nil),       // 8: HooksInit.Request
	(*HooksInit_Response)(nil),      // 9: HooksInit.Response
	nil,                             // 10: HooksInit.Request.ConfigEntry
	(*HooksName_Request)(nil),       // 11: HooksName.Request
	(*HooksName_Response)(nil),      // 12: HooksName.Response
	(*HooksVersion_Request)(nil),    // 13: HooksVersion.Request
	(*HooksVersion_Response)(nil),   // 14: HooksVersion.Response
	(*SuccessHook_Request)(nil),     // 15: SuccessHook.Request
	(*SuccessHook_Response)(nil),    // 16: SuccessHook.Response
	(*NoReleaseHook_Request)(nil),   // 17: NoReleaseHook.Request
	(*NoReleaseHook_Response)(nil),  // 18: NoReleaseHook.Response
	(*semrel.Commit)(nil),           // 19: Commit
	(*semrel.Release)(nil),          // 20: Release
	(*provider.RepositoryInfo)(nil), // 21: RepositoryInfo
}
var file_pkg_hooks_hooks_proto_depIdxs = []int32{
	19, // 0: SuccessHookConfig.commits:type_name -> Commit
	20, // 1: SuccessHookConfig.prev_release:type_name -> Release
	20, // 2: SuccessHookConfig.new_release:type_name -> Release
	21, // 3: SuccessHookConfig.repo_info:type_name -> RepositoryInfo
	0,  // 4: NoReleaseConfig.reason:type_name -> NoReleaseReason
	10, // 5: HooksInit.Request.config:type_name -> HooksInit.Request.ConfigEntry
	4,  // 6: SuccessHook.Request.config:type_name -> SuccessHookConfig
	6,  // 7: NoReleaseHook.Request.config:type_name -> NoReleaseConfig
	8,  // 8: HooksPlugin.Init:input_type -> HooksInit.Request
	11, // 9: HooksPlugin.Name:input_type -> HooksName.Request
	13, // 10: HooksPlugin.Version:input_type -> HooksVersion.Request
	15, // 11: HooksPlugin.Success:input_type -> SuccessHook.Request
	17, // 12: HooksPlugin.NoRelease:input_type -> NoReleaseHook.Request
	9,  // 13: HooksPlugin.Init:output_type -> HooksInit.Response
	12, // 14: HooksPlugin.Name:output_type -> HooksName.Response
	14, // 15: HooksPlugin.Version:output_type -> HooksVersion.Response
	16, // 16: HooksPlugin.Success:output_type -> SuccessHook.Response
	18, // 17: HooksPlugin.NoRelease:output_type -> NoReleaseHook.Response
	13, // [13:18] is the sub-list for method output_type
	8,  // [8:13] is the sub-list for method input_type
	8,  // [8:8] is the sub-list for extension type_name
	8,  // [8:8] is the sub-list for extension extendee
	0,  // [0:8] is the sub-list for field type_name
}

func init() { file_pkg_hooks_hooks_proto_init() }
func file_pkg_hooks_hooks_proto_init() {
	if File_pkg_hooks_hooks_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pkg_hooks_hooks_proto_rawDesc), len(file_pkg_hooks_hooks_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   18,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pkg_hooks_hooks_proto_goTypes,
		DependencyIndexes: file_pkg_hooks_hooks_proto_depIdxs,
		EnumInfos:         file_pkg_hooks_hooks_proto_enumTypes,
		MessageInfos:      file_pkg_hooks_hooks_proto_msgTypes,
	}.Build()
	File_pkg_hooks_hooks_proto = out.File
	file_pkg_hooks_hooks_proto_goTypes = nil
	file_pkg_hooks_hooks_proto_depIdxs = nil
}
