// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.1
// source: pkg/provider/provider.proto

package provider

import (
	semrel "github.com/go-semantic-release/semantic-release/v2/pkg/semrel"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RepositoryInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Owner         string                 `protobuf:"bytes,1,opt,name=owner,proto3" json:"owner,omitempty"`
	Repo          string                 `protobuf:"bytes,2,opt,name=repo,proto3" json:"repo,omitempty"`
	DefaultBranch string                 `protobuf:"bytes,3,opt,name=default_branch,json=defaultBranch,proto3" json:"default_branch,omitempty"`
	Private       bool                   `protobuf:"varint,4,opt,name=private,proto3" json:"private,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RepositoryInfo) Reset() {
	*x = RepositoryInfo{}
	mi := &file_pkg_provider_provider_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RepositoryInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RepositoryInfo) ProtoMessage() {}

func (x *RepositoryInfo) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_provider_provider_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RepositoryInfo.ProtoReflect.Descriptor instead.
func (*RepositoryInfo) Descriptor() ([]byte, []int) {
	return file_pkg_provider_provider_proto_rawDescGZIP(), []int{0}
}

func (x *RepositoryInfo) GetOwner() string {
	if x != nil {
		return x.Owner
	}
	return ""
}

func (x *RepositoryInfo) GetRepo() string {
	if x != nil {
		return x.Repo
	}
	return ""
}

func (x *RepositoryInfo) GetDefaultBranch() string {
	if x != nil {
		return x.DefaultBranch
	}
	return ""
}

func (x *RepositoryInfo) GetPrivate() bool {
	if x != nil {
		return x.Private
	}
	return false
}

type CreateReleaseConfig struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Changelog     string                 `protobuf:"bytes,1,opt,name=changelog,proto3" json:"changelog,omitempty"`
	NewVersion    string                 `protobuf:"bytes,2,opt,name=new_version,json=newVersion,proto3" json:"new_version,omitempty"`
	Prerelease    bool                   `protobuf:"varint,3,opt,name=prerelease,proto3" json:"prerelease,omitempty"`
	Branch        string                 `protobuf:"bytes,4,opt,name=branch,proto3" json:"branch,omitempty"`
	SHA           string                 `protobuf:"bytes,5,opt,name=SHA,proto3" json:"SHA,omitempty"`
	Draft         bool                   `protobuf:"varint,6,opt,name=draft,proto3" json:"draft,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateReleaseConfig) Reset() {
	*x = CreateReleaseConfig{}
	mi := &file_pkg_provider_provider_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateReleaseConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateReleaseConfig) ProtoMessage() {}

func (x *CreateReleaseConfig) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_provider_provider_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateReleaseConfig.ProtoReflect.Descriptor instead.
func (*CreateReleaseConfig) Descriptor() ([]byte, []int) {
	return file_pkg_provider_provider_proto_rawDescGZIP(), []int{1}
}

func (x *CreateReleaseConfig) GetChangelog() string {
	if x != nil {
		return x.Changelog
	}
	return ""
}

func (x *CreateReleaseConfig) GetNewVersion() string {
	if x != nil {
		return x.NewVersion
	}
	return ""
}

func (x *CreateReleaseConfig) GetPrerelease() bool {
	if x != nil {
		return x.Prerelease
	}
	return false
}

func (x *CreateReleaseConfig) GetBranch() string {
	if x != nil {
		return x.Branch
	}
	return ""
}

func (x *CreateReleaseConfig) GetSHA() string {
	if x != nil {
		return x.SHA
	}
	return ""
}

func (x *CreateReleaseConfig) GetDraft() bool {
	if x != nil {
		return x.Draft
	}
	return false
}

type ProviderInit struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProviderInit) Reset() {
	*x = ProviderInit{}
	mi := &file_pkg_provider_provider_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProviderInit) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProviderInit) ProtoMessage() {}

func (x *ProviderInit) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_provider_provider_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProviderInit.ProtoReflect.Descriptor instead.
func (*ProviderInit) Descriptor() ([]byte, []int) {
	return file_pkg_provider_provider_proto_rawDescGZIP(), []int{2}
}

type ProviderName struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProviderName) Reset() {
	*x = ProviderName{}
	mi := &file_pkg_provider_provider_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProviderName) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProviderName) ProtoMessage() {}

func (x *ProviderName) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_provider_provider_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProviderName.ProtoReflect.Descriptor instead.
func (*ProviderName) Descriptor() ([]byte, []int) {
	return file_pkg_provider_provider_proto_rawDescGZIP(), []int{3}
}

type ProviderVersion struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProviderVersion) Reset() {
	*x = ProviderVersion{}
	mi := &file_pkg_provider_provider_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProviderVersion) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProviderVersion) ProtoMessage() {}

func (x *ProviderVersion) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_provider_provider_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProviderVersion.ProtoReflect.Descriptor instead.
func (*ProviderVersion) Descriptor() ([]byte, []int) {
	return file_pkg_provider_provider_proto_rawDescGZIP(), []int{4}
}

type GetInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetInfo) Reset() {
	*x = GetInfo{}
	mi := &file_pkg_provider_provider_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetInfo) ProtoMessage() {}

func (x *GetInfo) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_provider_provider_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetInfo.ProtoReflect.Descriptor instead.
func (*GetInfo) Descriptor() ([]byte, []int) {
	return file_pkg_provider_provider_proto_rawDescGZIP(), []int{5}
}

type GetCommits struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCommits) Reset() {
	*x = GetCommits{}
	mi := &file_pkg_provider_provider_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCommits) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCommits) ProtoMessage() {}

func (x *GetCommits) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_provider_provider_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCommits.ProtoReflect.Descriptor instead.
func (*GetCommits) Descriptor() ([]byte, []int) {
	return file_pkg_provider_provider_proto_rawDescGZIP(), []int{6}
}

type GetReleases struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetReleases) Reset() {
	*x = GetReleases{}
	mi := &file_pkg_provider_provider_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetReleases) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetReleases) ProtoMessage() {}

func (x *GetReleases) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_provider_provider_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetReleases.ProtoReflect.Descriptor instead.
func (*GetReleases) Descriptor() ([]byte, []int) {
	return file_pkg_provider_provider_proto_rawDescGZIP(), []int{7}
}

type CreateRelease struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateRelease) Reset() {
	*x = CreateRelease{}
	mi := &file_pkg_provider_provider_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateRelease) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateRelease) ProtoMessage() {}

func (x *CreateRelease) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_provider_provider_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateRelease.ProtoReflect.Descriptor instead.
func (*CreateRelease) Descriptor() ([]byte, []int) {
	return file_pkg_provider_provider_proto_rawDescGZIP(), []int{8}
}

type ProviderInit_Request struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Config        map[string]string      `protobuf:"bytes,1,rep,name=config,proto3" json:"config,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProviderInit_Request) Reset() {
	*x = ProviderInit_Request{}
	mi := &file_pkg_provider_provider_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProviderInit_Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProviderInit_Request) ProtoMessage() {}

func (x *ProviderInit_Request) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_provider_provider_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProviderInit_Request.ProtoReflect.Descriptor instead.
func (*ProviderInit_Request) Descriptor() ([]byte, []int) {
	return file_pkg_provider_provider_proto_rawDescGZIP(), []int{2, 0}
}

func (x *ProviderInit_Request) GetConfig() map[string]string {
	if x != nil {
		return x.Config
	}
	return nil
}

type ProviderInit_Response struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Error         string                 `protobuf:"bytes,1,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProviderInit_Response) Reset() {
	*x = ProviderInit_Response{}
	mi := &file_pkg_provider_provider_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProviderInit_Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProviderInit_Response) ProtoMessage() {}

func (x *ProviderInit_Response) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_provider_provider_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProviderInit_Response.ProtoReflect.Descriptor instead.
func (*ProviderInit_Response) Descriptor() ([]byte, []int) {
	return file_pkg_provider_provider_proto_rawDescGZIP(), []int{2, 1}
}

func (x *ProviderInit_Response) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type ProviderName_Request struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProviderName_Request) Reset() {
	*x = ProviderName_Request{}
	mi := &file_pkg_provider_provider_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProviderName_Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProviderName_Request) ProtoMessage() {}

func (x *ProviderName_Request) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_provider_provider_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProviderName_Request.ProtoReflect.Descriptor instead.
func (*ProviderName_Request) Descriptor() ([]byte, []int) {
	return file_pkg_provider_provider_proto_rawDescGZIP(), []int{3, 0}
}

type ProviderName_Response struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProviderName_Response) Reset() {
	*x = ProviderName_Response{}
	mi := &file_pkg_provider_provider_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProviderName_Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProviderName_Response) ProtoMessage() {}

func (x *ProviderName_Response) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_provider_provider_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProviderName_Response.ProtoReflect.Descriptor instead.
func (*ProviderName_Response) Descriptor() ([]byte, []int) {
	return file_pkg_provider_provider_proto_rawDescGZIP(), []int{3, 1}
}

func (x *ProviderName_Response) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type ProviderVersion_Request struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProviderVersion_Request) Reset() {
	*x = ProviderVersion_Request{}
	mi := &file_pkg_provider_provider_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProviderVersion_Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProviderVersion_Request) ProtoMessage() {}

func (x *ProviderVersion_Request) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_provider_provider_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProviderVersion_Request.ProtoReflect.Descriptor instead.
func (*ProviderVersion_Request) Descriptor() ([]byte, []int) {
	return file_pkg_provider_provider_proto_rawDescGZIP(), []int{4, 0}
}

type ProviderVersion_Response struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Version       string                 `protobuf:"bytes,1,opt,name=version,proto3" json:"version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProviderVersion_Response) Reset() {
	*x = ProviderVersion_Response{}
	mi := &file_pkg_provider_provider_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProviderVersion_Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProviderVersion_Response) ProtoMessage() {}

func (x *ProviderVersion_Response) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_provider_provider_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProviderVersion_Response.ProtoReflect.Descriptor instead.
func (*ProviderVersion_Response) Descriptor() ([]byte, []int) {
	return file_pkg_provider_provider_proto_rawDescGZIP(), []int{4, 1}
}

func (x *ProviderVersion_Response) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

type GetInfo_Request struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetInfo_Request) Reset() {
	*x = GetInfo_Request{}
	mi := &file_pkg_provider_provider_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetInfo_Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetInfo_Request) ProtoMessage() {}

func (x *GetInfo_Request) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_provider_provider_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetInfo_Request.ProtoReflect.Descriptor instead.
func (*GetInfo_Request) Descriptor() ([]byte, []int) {
	return file_pkg_provider_provider_proto_rawDescGZIP(), []int{5, 0}
}

type GetInfo_Response struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Info          *RepositoryInfo        `protobuf:"bytes,1,opt,name=info,proto3" json:"info,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetInfo_Response) Reset() {
	*x = GetInfo_Response{}
	mi := &file_pkg_provider_provider_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetInfo_Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetInfo_Response) ProtoMessage() {}

func (x *GetInfo_Response) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_provider_provider_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetInfo_Response.ProtoReflect.Descriptor instead.
func (*GetInfo_Response) Descriptor() ([]byte, []int) {
	return file_pkg_provider_provider_proto_rawDescGZIP(), []int{5, 1}
}

func (x *GetInfo_Response) GetInfo() *RepositoryInfo {
	if x != nil {
		return x.Info
	}
	return nil
}

func (x *GetInfo_Response) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type GetCommits_Request struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ToSha         string                 `protobuf:"bytes,1,opt,name=to_sha,json=toSha,proto3" json:"to_sha,omitempty"`
	FromSha       string                 `protobuf:"bytes,2,opt,name=from_sha,json=fromSha,proto3" json:"from_sha,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCommits_Request) Reset() {
	*x = GetCommits_Request{}
	mi := &file_pkg_provider_provider_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCommits_Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCommits_Request) ProtoMessage() {}

func (x *GetCommits_Request) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_provider_provider_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCommits_Request.ProtoReflect.Descriptor instead.
func (*GetCommits_Request) Descriptor() ([]byte, []int) {
	return file_pkg_provider_provider_proto_rawDescGZIP(), []int{6, 0}
}

func (x *GetCommits_Request) GetToSha() string {
	if x != nil {
		return x.ToSha
	}
	return ""
}

func (x *GetCommits_Request) GetFromSha() string {
	if x != nil {
		return x.FromSha
	}
	return ""
}

type GetCommits_Response struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RawCommits    []*semrel.RawCommit    `protobuf:"bytes,1,rep,name=raw_commits,json=rawCommits,proto3" json:"raw_commits,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCommits_Response) Reset() {
	*x = GetCommits_Response{}
	mi := &file_pkg_provider_provider_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCommits_Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCommits_Response) ProtoMessage() {}

func (x *GetCommits_Response) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_provider_provider_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCommits_Response.ProtoReflect.Descriptor instead.
func (*GetCommits_Response) Descriptor() ([]byte, []int) {
	return file_pkg_provider_provider_proto_rawDescGZIP(), []int{6, 1}
}

func (x *GetCommits_Response) GetRawCommits() []*semrel.RawCommit {
	if x != nil {
		return x.RawCommits
	}
	return nil
}

func (x *GetCommits_Response) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type GetReleases_Request struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Regexp        string                 `protobuf:"bytes,1,opt,name=regexp,proto3" json:"regexp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetReleases_Request) Reset() {
	*x = GetReleases_Request{}
	mi := &file_pkg_provider_provider_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetReleases_Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetReleases_Request) ProtoMessage() {}

func (x *GetReleases_Request) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_provider_provider_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetReleases_Request.ProtoReflect.Descriptor instead.
func (*GetReleases_Request) Descriptor() ([]byte, []int) {
	return file_pkg_provider_provider_proto_rawDescGZIP(), []int{7, 0}
}

func (x *GetReleases_Request) GetRegexp() string {
	if x != nil {
		return x.Regexp
	}
	return ""
}

type GetReleases_Response struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Releases      []*semrel.Release      `protobuf:"bytes,1,rep,name=releases,proto3" json:"releases,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetReleases_Response) Reset() {
	*x = GetReleases_Response{}
	mi := &file_pkg_provider_provider_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetReleases_Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetReleases_Response) ProtoMessage() {}

func (x *GetReleases_Response) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_provider_provider_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetReleases_Response.ProtoReflect.Descriptor instead.
func (*GetReleases_Response) Descriptor() ([]byte, []int) {
	return file_pkg_provider_provider_proto_rawDescGZIP(), []int{7, 1}
}

func (x *GetReleases_Response) GetReleases() []*semrel.Release {
	if x != nil {
		return x.Releases
	}
	return nil
}

func (x *GetReleases_Response) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type CreateRelease_Request struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Config        *CreateReleaseConfig   `protobuf:"bytes,1,opt,name=config,proto3" json:"config,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateRelease_Request) Reset() {
	*x = CreateRelease_Request{}
	mi := &file_pkg_provider_provider_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateRelease_Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateRelease_Request) ProtoMessage() {}

func (x *CreateRelease_Request) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_provider_provider_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateRelease_Request.ProtoReflect.Descriptor instead.
func (*CreateRelease_Request) Descriptor() ([]byte, []int) {
	return file_pkg_provider_provider_proto_rawDescGZIP(), []int{8, 0}
}

func (x *CreateRelease_Request) GetConfig() *CreateReleaseConfig {
	if x != nil {
		return x.Config
	}
	return nil
}

type CreateRelease_Response struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Error         string                 `protobuf:"bytes,1,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateRelease_Response) Reset() {
	*x = CreateRelease_Response{}
	mi := &file_pkg_provider_provider_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateRelease_Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateRelease_Response) ProtoMessage() {}

func (x *CreateRelease_Response) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_provider_provider_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateRelease_Response.ProtoReflect.Descriptor instead.
func (*CreateRelease_Response) Descriptor() ([]byte, []int) {
	return file_pkg_provider_provider_proto_rawDescGZIP(), []int{8, 1}
}

func (x *CreateRelease_Response) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

var File_pkg_provider_provider_proto protoreflect.FileDescriptor

const file_pkg_provider_provider_proto_rawDesc = "" +
	"\n" +
	"\x1bpkg/provider/provider.proto\x1a\x18pkg/semrel/structs.proto\"{\n" +
	"\x0eRepositoryInfo\x12\x14\n" +
	"\x05owner\x18\x01 \x01(\tR\x05owner\x12\x12\n" +
	"\x04repo\x18\x02 \x01(\tR\x04repo\x12%\n" +
	"\x0edefault_branch\x18\x03 \x01(\tR\rdefaultBranch\x12\x18\n" +
	"\aprivate\x18\x04 \x01(\bR\aprivate\"\xb4\x01\n" +
	"\x13CreateReleaseConfig\x12\x1c\n" +
	"\tchangelog\x18\x01 \x01(\tR\tchangelog\x12\x1f\n" +
	"\vnew_version\x18\x02 \x01(\tR\n" +
	"newVersion\x12\x1e\n" +
	"\n" +
	"prerelease\x18\x03 \x01(\bR\n" +
	"prerelease\x12\x16\n" +
	"\x06branch\x18\x04 \x01(\tR\x06branch\x12\x10\n" +
	"\x03SHA\x18\x05 \x01(\tR\x03SHA\x12\x14\n" +
	"\x05draft\x18\x06 \x01(\bR\x05draft\"\xb1\x01\n" +
	"\fProviderInit\x1a\x7f\n" +
	"\aRequest\x129\n" +
	"\x06config\x18\x01 \x03(\v2!.ProviderInit.Request.ConfigEntryR\x06config\x1a9\n" +
	"\vConfigEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\x1a \n" +
	"\bResponse\x12\x14\n" +
	"\x05error\x18\x01 \x01(\tR\x05error\"9\n" +
	"\fProviderName\x1a\t\n" +
	"\aRequest\x1a\x1e\n" +
	"\bResponse\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\"B\n" +
	"\x0fProviderVersion\x1a\t\n" +
	"\aRequest\x1a$\n" +
	"\bResponse\x12\x18\n" +
	"\aversion\x18\x01 \x01(\tR\aversion\"[\n" +
	"\aGetInfo\x1a\t\n" +
	"\aRequest\x1aE\n" +
	"\bResponse\x12#\n" +
	"\x04info\x18\x01 \x01(\v2\x0f.RepositoryInfoR\x04info\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\"\x98\x01\n" +
	"\n" +
	"GetCommits\x1a;\n" +
	"\aRequest\x12\x15\n" +
	"\x06to_sha\x18\x01 \x01(\tR\x05toSha\x12\x19\n" +
	"\bfrom_sha\x18\x02 \x01(\tR\afromSha\x1aM\n" +
	"\bResponse\x12+\n" +
	"\vraw_commits\x18\x01 \x03(\v2\n" +
	".RawCommitR\n" +
	"rawCommits\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\"x\n" +
	"\vGetReleases\x1a!\n" +
	"\aRequest\x12\x16\n" +
	"\x06regexp\x18\x01 \x01(\tR\x06regexp\x1aF\n" +
	"\bResponse\x12$\n" +
	"\breleases\x18\x01 \x03(\v2\b.ReleaseR\breleases\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\"j\n" +
	"\rCreateRelease\x1a7\n" +
	"\aRequest\x12,\n" +
	"\x06config\x18\x01 \x01(\v2\x14.CreateReleaseConfigR\x06config\x1a \n" +
	"\bResponse\x12\x14\n" +
	"\x05error\x18\x01 \x01(\tR\x05error2\xa5\x03\n" +
	"\x0eProviderPlugin\x125\n" +
	"\x04Init\x12\x15.ProviderInit.Request\x1a\x16.ProviderInit.Response\x125\n" +
	"\x04Name\x12\x15.ProviderName.Request\x1a\x16.ProviderName.Response\x12>\n" +
	"\aVersion\x12\x18.ProviderVersion.Request\x1a\x19.ProviderVersion.Response\x12.\n" +
	"\aGetInfo\x12\x10.GetInfo.Request\x1a\x11.GetInfo.Response\x127\n" +
	"\n" +
	"GetCommits\x12\x13.GetCommits.Request\x1a\x14.GetCommits.Response\x12:\n" +
	"\vGetReleases\x12\x14.GetReleases.Request\x1a\x15.GetReleases.Response\x12@\n" +
	"\rCreateRelease\x12\x16.CreateRelease.Request\x1a\x17.CreateRelease.ResponseBAZ?github.com/go-semantic-release/semantic-release/v2/pkg/providerb\x06proto3"

var (
	file_pkg_provider_provider_proto_rawDescOnce sync.Once
	file_pkg_provider_provider_proto_rawDescData []byte
)

func file_pkg_provider_provider_proto_rawDescGZIP() []byte {
	file_pkg_provider_provider_proto_rawDescOnce.Do(func() {
		file_pkg_provider_provider_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pkg_provider_provider_proto_rawDesc), len(file_pkg_provider_provider_proto_rawDesc)))
	})
	return file_pkg_provider_provider_proto_rawDescData
}

var file_pkg_provider_provider_proto_msgTypes = make([]protoimpl.MessageInfo, 24)
var file_pkg_provider_provider_proto_goTypes = []any{
	(*RepositoryInfo)(nil),           // 0: RepositoryInfo
	(*CreateReleaseConfig)(nil),      // 1: CreateReleaseConfig
	(*ProviderInit)(nil),             // 2: ProviderInit
	(*ProviderName)(nil),             // 3: ProviderName
	(*ProviderVersion)(nil),          // 4: ProviderVersion
	(*GetInfo)(nil),                  // 5: GetInfo
	(*GetCommits)(nil),               // 6: GetCommits
	(*GetReleases)(nil),              // 7: GetReleases
	(*CreateRelease)(nil),            // 8: CreateRelease
	(*ProviderInit_Request)(nil),     // 9: ProviderInit.Request
	(*ProviderInit_Response)(nil),    // 10: ProviderInit.Response
	nil,                              // 11: ProviderInit.Request.ConfigEntry
	(*ProviderName_Request)(nil),     // 12: ProviderName.Request
	(*ProviderName_Response)(nil),    // 13: ProviderName.Response
	(*ProviderVersion_Request)(nil),  // 14: ProviderVersion.Request
	(*ProviderVersion_Response)(nil), // 15: ProviderVersion.Response
	(*GetInfo_Request)(nil),          // 16: GetInfo.Request
	(*GetInfo_Response)(nil),         // 17: GetInfo.Response
	(*GetCommits_Request)(nil),       // 18: GetCommits.Request
	(*GetCommits_Response)(nil),      // 19: GetCommits.Response
	(*GetReleases_Request)(nil),      // 20: GetReleases.Request
	(*GetReleases_Response)(nil),     // 21: GetReleases.Response
	(*CreateRelease_Request)(nil),    // 22: CreateRelease.Request
	(*CreateRelease_Response)(nil),   // 23: CreateRelease.Response
	(*semrel.RawCommit)(nil),         // 24: RawCommit
	(*semrel.Release)(nil),           // 25: Release
}
var file_pkg_provider_provider_proto_depIdxs = []int32{
	11, // 0: ProviderInit.Request.config:type_name -> ProviderInit.Request.ConfigEntry
	0,  // 1: GetInfo.Response.info:type_name -> RepositoryInfo
	24, // 2: GetCommits.Response.raw_commits:type_name -> RawCommit
	25, // 3: GetReleases.Response.releases:type_name -> Release
	1,  // 4: CreateRelease.Request.config:type_name -> CreateReleaseConfig
	9,  // 5: ProviderPlugin.Init:input_type -> ProviderInit.Request
	12, // 6: ProviderPlugin.Name:input_type -> ProviderName.Request
	14, // 7: ProviderPlugin.Version:input_type -> ProviderVersion.Request
	16, // 8: ProviderPlugin.GetInfo:input_type -> GetInfo.Request
	18, // 9: ProviderPlugin.GetCommits:input_type -> GetCommits.Request
	20, // 10: ProviderPlugin.GetReleases:input_type -> GetReleases.Request
	22, // 11: ProviderPlugin.CreateRelease:input_type -> CreateRelease.Request
	10, // 12: ProviderPlugin.Init:output_type -> ProviderInit.Response
	13, // 13: ProviderPlugin.Name:output_type -> ProviderName.Response
	15, // 14: ProviderPlugin.Version:output_type -> ProviderVersion.Response
	17, // 15: ProviderPlugin.GetInfo:output_type -> GetInfo.Response
	19, // 16: ProviderPlugin.GetCommits:output_type -> GetCommits.Response
	21, // 17: ProviderPlugin.GetReleases:output_type -> GetReleases.Response
	23, // 18: ProviderPlugin.CreateRelease:output_type -> CreateRelease.Response
	12, // [12:19] is the sub-list for method output_type
	5,  // [5:12] is the sub-list for method input_type
	5,  // [5:5] is the sub-list for extension type_name
	5,  // [5:5] is the sub-list for extension extendee
	0,  // [0:5] is the sub-list for field type_name
}

func init() { file_pkg_provider_provider_proto_init() }
func file_pkg_provider_provider_proto_init() {
	if File_pkg_provider_provider_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pkg_provider_provider_proto_rawDesc), len(file_pkg_provider_provider_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   24,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pkg_provider_provider_proto_goTypes,
		DependencyIndexes: file_pkg_provider_provider_proto_depIdxs,
		MessageInfos:      file_pkg_provider_provider_proto_msgTypes,
	}.Build()
	File_pkg_provider_provider_proto = out.File
	file_pkg_provider_provider_proto_goTypes = nil
	file_pkg_provider_provider_proto_depIdxs = nil
}
