// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.1
// source: pkg/config/config.proto

package config

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Config is a complete set of app configuration
type Config struct {
	state                                 protoimpl.MessageState `protogen:"open.v1"`
	Token                                 string                 `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	ProviderPlugin                        string                 `protobuf:"bytes,2,opt,name=provider_plugin,json=providerPlugin,proto3" json:"provider_plugin,omitempty"`
	ProviderOpts                          map[string]string      `protobuf:"bytes,3,rep,name=provider_opts,json=providerOpts,proto3" json:"provider_opts,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	CommitAnalyzerPlugin                  string                 `protobuf:"bytes,4,opt,name=commit_analyzer_plugin,json=commitAnalyzerPlugin,proto3" json:"commit_analyzer_plugin,omitempty"`
	CommitAnalyzerOpts                    map[string]string      `protobuf:"bytes,5,rep,name=commit_analyzer_opts,json=commitAnalyzerOpts,proto3" json:"commit_analyzer_opts,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	CiConditionPlugin                     string                 `protobuf:"bytes,6,opt,name=ci_condition_plugin,json=ciConditionPlugin,proto3" json:"ci_condition_plugin,omitempty"`
	CiConditionOpts                       map[string]string      `protobuf:"bytes,7,rep,name=ci_condition_opts,json=ciConditionOpts,proto3" json:"ci_condition_opts,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	ChangelogGeneratorPlugin              string                 `protobuf:"bytes,8,opt,name=changelog_generator_plugin,json=changelogGeneratorPlugin,proto3" json:"changelog_generator_plugin,omitempty"`
	ChangelogGeneratorOpts                map[string]string      `protobuf:"bytes,9,rep,name=changelog_generator_opts,json=changelogGeneratorOpts,proto3" json:"changelog_generator_opts,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Changelog                             string                 `protobuf:"bytes,10,opt,name=changelog,proto3" json:"changelog,omitempty"`
	FilesUpdaterPlugins                   []string               `protobuf:"bytes,11,rep,name=files_updater_plugins,json=filesUpdaterPlugins,proto3" json:"files_updater_plugins,omitempty"`
	FilesUpdaterOpts                      map[string]string      `protobuf:"bytes,12,rep,name=files_updater_opts,json=filesUpdaterOpts,proto3" json:"files_updater_opts,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	HooksPlugins                          []string               `protobuf:"bytes,13,rep,name=hooks_plugins,json=hooksPlugins,proto3" json:"hooks_plugins,omitempty"`
	HooksOpts                             map[string]string      `protobuf:"bytes,14,rep,name=hooks_opts,json=hooksOpts,proto3" json:"hooks_opts,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	UpdateFiles                           []string               `protobuf:"bytes,15,rep,name=update_files,json=updateFiles,proto3" json:"update_files,omitempty"`
	Match                                 string                 `protobuf:"bytes,16,opt,name=match,proto3" json:"match,omitempty"`
	VersionFile                           bool                   `protobuf:"varint,17,opt,name=version_file,json=versionFile,proto3" json:"version_file,omitempty"`
	Prerelease                            bool                   `protobuf:"varint,18,opt,name=prerelease,proto3" json:"prerelease,omitempty"`
	Ghr                                   bool                   `protobuf:"varint,19,opt,name=ghr,proto3" json:"ghr,omitempty"`
	NoCi                                  bool                   `protobuf:"varint,20,opt,name=no_ci,json=noCi,proto3" json:"no_ci,omitempty"`
	Dry                                   bool                   `protobuf:"varint,21,opt,name=dry,proto3" json:"dry,omitempty"`
	AllowInitialDevelopmentVersions       bool                   `protobuf:"varint,22,opt,name=allow_initial_development_versions,json=allowInitialDevelopmentVersions,proto3" json:"allow_initial_development_versions,omitempty"`
	AllowNoChanges                        bool                   `protobuf:"varint,23,opt,name=allow_no_changes,json=allowNoChanges,proto3" json:"allow_no_changes,omitempty"`
	ForceBumpPatchVersion                 bool                   `protobuf:"varint,24,opt,name=force_bump_patch_version,json=forceBumpPatchVersion,proto3" json:"force_bump_patch_version,omitempty"`
	MaintainedVersion                     string                 `protobuf:"bytes,25,opt,name=maintained_version,json=maintainedVersion,proto3" json:"maintained_version,omitempty"`
	PrependChangelog                      bool                   `protobuf:"varint,26,opt,name=prepend_changelog,json=prependChangelog,proto3" json:"prepend_changelog,omitempty"`
	DownloadPlugins                       bool                   `protobuf:"varint,27,opt,name=download_plugins,json=downloadPlugins,proto3" json:"download_plugins,omitempty"`
	ShowProgress                          bool                   `protobuf:"varint,28,opt,name=show_progress,json=showProgress,proto3" json:"show_progress,omitempty"`
	AllowMaintainedVersionOnDefaultBranch bool                   `protobuf:"varint,29,opt,name=allow_maintained_version_on_default_branch,json=allowMaintainedVersionOnDefaultBranch,proto3" json:"allow_maintained_version_on_default_branch,omitempty"`
	PluginResolver                        string                 `protobuf:"bytes,30,opt,name=plugin_resolver,json=pluginResolver,proto3" json:"plugin_resolver,omitempty"`
	PluginResolverEndpoint                string                 `protobuf:"bytes,31,opt,name=plugin_resolver_endpoint,json=pluginResolverEndpoint,proto3" json:"plugin_resolver_endpoint,omitempty"`
	PluginResolverDisableBatchPrefetch    bool                   `protobuf:"varint,32,opt,name=plugin_resolver_disable_batch_prefetch,json=pluginResolverDisableBatchPrefetch,proto3" json:"plugin_resolver_disable_batch_prefetch,omitempty"`
	UpdateFilesBefore                     []string               `protobuf:"bytes,33,rep,name=update_files_before,json=updateFilesBefore,proto3" json:"update_files_before,omitempty"`
	unknownFields                         protoimpl.UnknownFields
	sizeCache                             protoimpl.SizeCache
}

func (x *Config) Reset() {
	*x = Config{}
	mi := &file_pkg_config_config_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Config) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Config) ProtoMessage() {}

func (x *Config) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_config_config_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Config.ProtoReflect.Descriptor instead.
func (*Config) Descriptor() ([]byte, []int) {
	return file_pkg_config_config_proto_rawDescGZIP(), []int{0}
}

func (x *Config) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *Config) GetProviderPlugin() string {
	if x != nil {
		return x.ProviderPlugin
	}
	return ""
}

func (x *Config) GetProviderOpts() map[string]string {
	if x != nil {
		return x.ProviderOpts
	}
	return nil
}

func (x *Config) GetCommitAnalyzerPlugin() string {
	if x != nil {
		return x.CommitAnalyzerPlugin
	}
	return ""
}

func (x *Config) GetCommitAnalyzerOpts() map[string]string {
	if x != nil {
		return x.CommitAnalyzerOpts
	}
	return nil
}

func (x *Config) GetCiConditionPlugin() string {
	if x != nil {
		return x.CiConditionPlugin
	}
	return ""
}

func (x *Config) GetCiConditionOpts() map[string]string {
	if x != nil {
		return x.CiConditionOpts
	}
	return nil
}

func (x *Config) GetChangelogGeneratorPlugin() string {
	if x != nil {
		return x.ChangelogGeneratorPlugin
	}
	return ""
}

func (x *Config) GetChangelogGeneratorOpts() map[string]string {
	if x != nil {
		return x.ChangelogGeneratorOpts
	}
	return nil
}

func (x *Config) GetChangelog() string {
	if x != nil {
		return x.Changelog
	}
	return ""
}

func (x *Config) GetFilesUpdaterPlugins() []string {
	if x != nil {
		return x.FilesUpdaterPlugins
	}
	return nil
}

func (x *Config) GetFilesUpdaterOpts() map[string]string {
	if x != nil {
		return x.FilesUpdaterOpts
	}
	return nil
}

func (x *Config) GetHooksPlugins() []string {
	if x != nil {
		return x.HooksPlugins
	}
	return nil
}

func (x *Config) GetHooksOpts() map[string]string {
	if x != nil {
		return x.HooksOpts
	}
	return nil
}

func (x *Config) GetUpdateFiles() []string {
	if x != nil {
		return x.UpdateFiles
	}
	return nil
}

func (x *Config) GetMatch() string {
	if x != nil {
		return x.Match
	}
	return ""
}

func (x *Config) GetVersionFile() bool {
	if x != nil {
		return x.VersionFile
	}
	return false
}

func (x *Config) GetPrerelease() bool {
	if x != nil {
		return x.Prerelease
	}
	return false
}

func (x *Config) GetGhr() bool {
	if x != nil {
		return x.Ghr
	}
	return false
}

func (x *Config) GetNoCi() bool {
	if x != nil {
		return x.NoCi
	}
	return false
}

func (x *Config) GetDry() bool {
	if x != nil {
		return x.Dry
	}
	return false
}

func (x *Config) GetAllowInitialDevelopmentVersions() bool {
	if x != nil {
		return x.AllowInitialDevelopmentVersions
	}
	return false
}

func (x *Config) GetAllowNoChanges() bool {
	if x != nil {
		return x.AllowNoChanges
	}
	return false
}

func (x *Config) GetForceBumpPatchVersion() bool {
	if x != nil {
		return x.ForceBumpPatchVersion
	}
	return false
}

func (x *Config) GetMaintainedVersion() string {
	if x != nil {
		return x.MaintainedVersion
	}
	return ""
}

func (x *Config) GetPrependChangelog() bool {
	if x != nil {
		return x.PrependChangelog
	}
	return false
}

func (x *Config) GetDownloadPlugins() bool {
	if x != nil {
		return x.DownloadPlugins
	}
	return false
}

func (x *Config) GetShowProgress() bool {
	if x != nil {
		return x.ShowProgress
	}
	return false
}

func (x *Config) GetAllowMaintainedVersionOnDefaultBranch() bool {
	if x != nil {
		return x.AllowMaintainedVersionOnDefaultBranch
	}
	return false
}

func (x *Config) GetPluginResolver() string {
	if x != nil {
		return x.PluginResolver
	}
	return ""
}

func (x *Config) GetPluginResolverEndpoint() string {
	if x != nil {
		return x.PluginResolverEndpoint
	}
	return ""
}

func (x *Config) GetPluginResolverDisableBatchPrefetch() bool {
	if x != nil {
		return x.PluginResolverDisableBatchPrefetch
	}
	return false
}

func (x *Config) GetUpdateFilesBefore() []string {
	if x != nil {
		return x.UpdateFilesBefore
	}
	return nil
}

var File_pkg_config_config_proto protoreflect.FileDescriptor

const file_pkg_config_config_proto_rawDesc = "" +
	"\n" +
	"\x17pkg/config/config.proto\"\x8f\x10\n" +
	"\x06Config\x12\x14\n" +
	"\x05token\x18\x01 \x01(\tR\x05token\x12'\n" +
	"\x0fprovider_plugin\x18\x02 \x01(\tR\x0eproviderPlugin\x12>\n" +
	"\rprovider_opts\x18\x03 \x03(\v2\x19.Config.ProviderOptsEntryR\fproviderOpts\x124\n" +
	"\x16commit_analyzer_plugin\x18\x04 \x01(\tR\x14commitAnalyzerPlugin\x12Q\n" +
	"\x14commit_analyzer_opts\x18\x05 \x03(\v2\x1f.Config.CommitAnalyzerOptsEntryR\x12commitAnalyzerOpts\x12.\n" +
	"\x13ci_condition_plugin\x18\x06 \x01(\tR\x11ciConditionPlugin\x12H\n" +
	"\x11ci_condition_opts\x18\a \x03(\v2\x1c.Config.CiConditionOptsEntryR\x0fciConditionOpts\x12<\n" +
	"\x1achangelog_generator_plugin\x18\b \x01(\tR\x18changelogGeneratorPlugin\x12]\n" +
	"\x18changelog_generator_opts\x18\t \x03(\v2#.Config.ChangelogGeneratorOptsEntryR\x16changelogGeneratorOpts\x12\x1c\n" +
	"\tchangelog\x18\n" +
	" \x01(\tR\tchangelog\x122\n" +
	"\x15files_updater_plugins\x18\v \x03(\tR\x13filesUpdaterPlugins\x12K\n" +
	"\x12files_updater_opts\x18\f \x03(\v2\x1d.Config.FilesUpdaterOptsEntryR\x10filesUpdaterOpts\x12#\n" +
	"\rhooks_plugins\x18\r \x03(\tR\fhooksPlugins\x125\n" +
	"\n" +
	"hooks_opts\x18\x0e \x03(\v2\x16.Config.HooksOptsEntryR\thooksOpts\x12!\n" +
	"\fupdate_files\x18\x0f \x03(\tR\vupdateFiles\x12\x14\n" +
	"\x05match\x18\x10 \x01(\tR\x05match\x12!\n" +
	"\fversion_file\x18\x11 \x01(\bR\vversionFile\x12\x1e\n" +
	"\n" +
	"prerelease\x18\x12 \x01(\bR\n" +
	"prerelease\x12\x10\n" +
	"\x03ghr\x18\x13 \x01(\bR\x03ghr\x12\x13\n" +
	"\x05no_ci\x18\x14 \x01(\bR\x04noCi\x12\x10\n" +
	"\x03dry\x18\x15 \x01(\bR\x03dry\x12K\n" +
	"\"allow_initial_development_versions\x18\x16 \x01(\bR\x1fallowInitialDevelopmentVersions\x12(\n" +
	"\x10allow_no_changes\x18\x17 \x01(\bR\x0eallowNoChanges\x127\n" +
	"\x18force_bump_patch_version\x18\x18 \x01(\bR\x15forceBumpPatchVersion\x12-\n" +
	"\x12maintained_version\x18\x19 \x01(\tR\x11maintainedVersion\x12+\n" +
	"\x11prepend_changelog\x18\x1a \x01(\bR\x10prependChangelog\x12)\n" +
	"\x10download_plugins\x18\x1b \x01(\bR\x0fdownloadPlugins\x12#\n" +
	"\rshow_progress\x18\x1c \x01(\bR\fshowProgress\x12Y\n" +
	"*allow_maintained_version_on_default_branch\x18\x1d \x01(\bR%allowMaintainedVersionOnDefaultBranch\x12'\n" +
	"\x0fplugin_resolver\x18\x1e \x01(\tR\x0epluginResolver\x128\n" +
	"\x18plugin_resolver_endpoint\x18\x1f \x01(\tR\x16pluginResolverEndpoint\x12R\n" +
	"&plugin_resolver_disable_batch_prefetch\x18  \x01(\bR\"pluginResolverDisableBatchPrefetch\x12.\n" +
	"\x13update_files_before\x18! \x03(\tR\x11updateFilesBefore\x1a?\n" +
	"\x11ProviderOptsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\x1aE\n" +
	"\x17CommitAnalyzerOptsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\x1aB\n" +
	"\x14CiConditionOptsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\x1aI\n" +
	"\x1bChangelogGeneratorOptsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\x1aC\n" +
	"\x15FilesUpdaterOptsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\x1a<\n" +
	"\x0eHooksOptsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01B?Z=github.com/go-semantic-release/semantic-release/v2/pkg/configb\x06proto3"

var (
	file_pkg_config_config_proto_rawDescOnce sync.Once
	file_pkg_config_config_proto_rawDescData []byte
)

func file_pkg_config_config_proto_rawDescGZIP() []byte {
	file_pkg_config_config_proto_rawDescOnce.Do(func() {
		file_pkg_config_config_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pkg_config_config_proto_rawDesc), len(file_pkg_config_config_proto_rawDesc)))
	})
	return file_pkg_config_config_proto_rawDescData
}

var file_pkg_config_config_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_pkg_config_config_proto_goTypes = []any{
	(*Config)(nil), // 0: Config
	nil,            // 1: Config.ProviderOptsEntry
	nil,            // 2: Config.CommitAnalyzerOptsEntry
	nil,            // 3: Config.CiConditionOptsEntry
	nil,            // 4: Config.ChangelogGeneratorOptsEntry
	nil,            // 5: Config.FilesUpdaterOptsEntry
	nil,            // 6: Config.HooksOptsEntry
}
var file_pkg_config_config_proto_depIdxs = []int32{
	1, // 0: Config.provider_opts:type_name -> Config.ProviderOptsEntry
	2, // 1: Config.commit_analyzer_opts:type_name -> Config.CommitAnalyzerOptsEntry
	3, // 2: Config.ci_condition_opts:type_name -> Config.CiConditionOptsEntry
	4, // 3: Config.changelog_generator_opts:type_name -> Config.ChangelogGeneratorOptsEntry
	5, // 4: Config.files_updater_opts:type_name -> Config.FilesUpdaterOptsEntry
	6, // 5: Config.hooks_opts:type_name -> Config.HooksOptsEntry
	6, // [6:6] is the sub-list for method output_type
	6, // [6:6] is the sub-list for method input_type
	6, // [6:6] is the sub-list for extension type_name
	6, // [6:6] is the sub-list for extension extendee
	0, // [0:6] is the sub-list for field type_name
}

func init() { file_pkg_config_config_proto_init() }
func file_pkg_config_config_proto_init() {
	if File_pkg_config_config_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pkg_config_config_proto_rawDesc), len(file_pkg_config_config_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_pkg_config_config_proto_goTypes,
		DependencyIndexes: file_pkg_config_config_proto_depIdxs,
		MessageInfos:      file_pkg_config_config_proto_msgTypes,
	}.Build()
	File_pkg_config_config_proto = out.File
	file_pkg_config_config_proto_goTypes = nil
	file_pkg_config_config_proto_depIdxs = nil
}
