// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.1
// source: pkg/generator/changelog_generator.proto

package generator

import (
	semrel "github.com/go-semantic-release/semantic-release/v2/pkg/semrel"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ChangelogGeneratorInit struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChangelogGeneratorInit) Reset() {
	*x = ChangelogGeneratorInit{}
	mi := &file_pkg_generator_changelog_generator_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChangelogGeneratorInit) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChangelogGeneratorInit) ProtoMessage() {}

func (x *ChangelogGeneratorInit) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_generator_changelog_generator_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChangelogGeneratorInit.ProtoReflect.Descriptor instead.
func (*ChangelogGeneratorInit) Descriptor() ([]byte, []int) {
	return file_pkg_generator_changelog_generator_proto_rawDescGZIP(), []int{0}
}

type ChangelogGeneratorName struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChangelogGeneratorName) Reset() {
	*x = ChangelogGeneratorName{}
	mi := &file_pkg_generator_changelog_generator_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChangelogGeneratorName) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChangelogGeneratorName) ProtoMessage() {}

func (x *ChangelogGeneratorName) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_generator_changelog_generator_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChangelogGeneratorName.ProtoReflect.Descriptor instead.
func (*ChangelogGeneratorName) Descriptor() ([]byte, []int) {
	return file_pkg_generator_changelog_generator_proto_rawDescGZIP(), []int{1}
}

type ChangelogGeneratorVersion struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChangelogGeneratorVersion) Reset() {
	*x = ChangelogGeneratorVersion{}
	mi := &file_pkg_generator_changelog_generator_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChangelogGeneratorVersion) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChangelogGeneratorVersion) ProtoMessage() {}

func (x *ChangelogGeneratorVersion) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_generator_changelog_generator_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChangelogGeneratorVersion.ProtoReflect.Descriptor instead.
func (*ChangelogGeneratorVersion) Descriptor() ([]byte, []int) {
	return file_pkg_generator_changelog_generator_proto_rawDescGZIP(), []int{2}
}

type ChangelogGeneratorConfig struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Commits       []*semrel.Commit       `protobuf:"bytes,1,rep,name=commits,proto3" json:"commits,omitempty"`
	LatestRelease *semrel.Release        `protobuf:"bytes,2,opt,name=latest_release,json=latestRelease,proto3" json:"latest_release,omitempty"`
	NewVersion    string                 `protobuf:"bytes,3,opt,name=new_version,json=newVersion,proto3" json:"new_version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChangelogGeneratorConfig) Reset() {
	*x = ChangelogGeneratorConfig{}
	mi := &file_pkg_generator_changelog_generator_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChangelogGeneratorConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChangelogGeneratorConfig) ProtoMessage() {}

func (x *ChangelogGeneratorConfig) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_generator_changelog_generator_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChangelogGeneratorConfig.ProtoReflect.Descriptor instead.
func (*ChangelogGeneratorConfig) Descriptor() ([]byte, []int) {
	return file_pkg_generator_changelog_generator_proto_rawDescGZIP(), []int{3}
}

func (x *ChangelogGeneratorConfig) GetCommits() []*semrel.Commit {
	if x != nil {
		return x.Commits
	}
	return nil
}

func (x *ChangelogGeneratorConfig) GetLatestRelease() *semrel.Release {
	if x != nil {
		return x.LatestRelease
	}
	return nil
}

func (x *ChangelogGeneratorConfig) GetNewVersion() string {
	if x != nil {
		return x.NewVersion
	}
	return ""
}

type GenerateChangelog struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GenerateChangelog) Reset() {
	*x = GenerateChangelog{}
	mi := &file_pkg_generator_changelog_generator_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GenerateChangelog) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GenerateChangelog) ProtoMessage() {}

func (x *GenerateChangelog) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_generator_changelog_generator_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GenerateChangelog.ProtoReflect.Descriptor instead.
func (*GenerateChangelog) Descriptor() ([]byte, []int) {
	return file_pkg_generator_changelog_generator_proto_rawDescGZIP(), []int{4}
}

type ChangelogGeneratorInit_Request struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Config        map[string]string      `protobuf:"bytes,1,rep,name=config,proto3" json:"config,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChangelogGeneratorInit_Request) Reset() {
	*x = ChangelogGeneratorInit_Request{}
	mi := &file_pkg_generator_changelog_generator_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChangelogGeneratorInit_Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChangelogGeneratorInit_Request) ProtoMessage() {}

func (x *ChangelogGeneratorInit_Request) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_generator_changelog_generator_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChangelogGeneratorInit_Request.ProtoReflect.Descriptor instead.
func (*ChangelogGeneratorInit_Request) Descriptor() ([]byte, []int) {
	return file_pkg_generator_changelog_generator_proto_rawDescGZIP(), []int{0, 0}
}

func (x *ChangelogGeneratorInit_Request) GetConfig() map[string]string {
	if x != nil {
		return x.Config
	}
	return nil
}

type ChangelogGeneratorInit_Response struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Error         string                 `protobuf:"bytes,1,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChangelogGeneratorInit_Response) Reset() {
	*x = ChangelogGeneratorInit_Response{}
	mi := &file_pkg_generator_changelog_generator_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChangelogGeneratorInit_Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChangelogGeneratorInit_Response) ProtoMessage() {}

func (x *ChangelogGeneratorInit_Response) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_generator_changelog_generator_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChangelogGeneratorInit_Response.ProtoReflect.Descriptor instead.
func (*ChangelogGeneratorInit_Response) Descriptor() ([]byte, []int) {
	return file_pkg_generator_changelog_generator_proto_rawDescGZIP(), []int{0, 1}
}

func (x *ChangelogGeneratorInit_Response) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type ChangelogGeneratorName_Request struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChangelogGeneratorName_Request) Reset() {
	*x = ChangelogGeneratorName_Request{}
	mi := &file_pkg_generator_changelog_generator_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChangelogGeneratorName_Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChangelogGeneratorName_Request) ProtoMessage() {}

func (x *ChangelogGeneratorName_Request) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_generator_changelog_generator_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChangelogGeneratorName_Request.ProtoReflect.Descriptor instead.
func (*ChangelogGeneratorName_Request) Descriptor() ([]byte, []int) {
	return file_pkg_generator_changelog_generator_proto_rawDescGZIP(), []int{1, 0}
}

type ChangelogGeneratorName_Response struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChangelogGeneratorName_Response) Reset() {
	*x = ChangelogGeneratorName_Response{}
	mi := &file_pkg_generator_changelog_generator_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChangelogGeneratorName_Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChangelogGeneratorName_Response) ProtoMessage() {}

func (x *ChangelogGeneratorName_Response) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_generator_changelog_generator_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChangelogGeneratorName_Response.ProtoReflect.Descriptor instead.
func (*ChangelogGeneratorName_Response) Descriptor() ([]byte, []int) {
	return file_pkg_generator_changelog_generator_proto_rawDescGZIP(), []int{1, 1}
}

func (x *ChangelogGeneratorName_Response) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type ChangelogGeneratorVersion_Request struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChangelogGeneratorVersion_Request) Reset() {
	*x = ChangelogGeneratorVersion_Request{}
	mi := &file_pkg_generator_changelog_generator_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChangelogGeneratorVersion_Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChangelogGeneratorVersion_Request) ProtoMessage() {}

func (x *ChangelogGeneratorVersion_Request) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_generator_changelog_generator_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChangelogGeneratorVersion_Request.ProtoReflect.Descriptor instead.
func (*ChangelogGeneratorVersion_Request) Descriptor() ([]byte, []int) {
	return file_pkg_generator_changelog_generator_proto_rawDescGZIP(), []int{2, 0}
}

type ChangelogGeneratorVersion_Response struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Version       string                 `protobuf:"bytes,1,opt,name=version,proto3" json:"version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChangelogGeneratorVersion_Response) Reset() {
	*x = ChangelogGeneratorVersion_Response{}
	mi := &file_pkg_generator_changelog_generator_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChangelogGeneratorVersion_Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChangelogGeneratorVersion_Response) ProtoMessage() {}

func (x *ChangelogGeneratorVersion_Response) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_generator_changelog_generator_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChangelogGeneratorVersion_Response.ProtoReflect.Descriptor instead.
func (*ChangelogGeneratorVersion_Response) Descriptor() ([]byte, []int) {
	return file_pkg_generator_changelog_generator_proto_rawDescGZIP(), []int{2, 1}
}

func (x *ChangelogGeneratorVersion_Response) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

type GenerateChangelog_Request struct {
	state         protoimpl.MessageState    `protogen:"open.v1"`
	Config        *ChangelogGeneratorConfig `protobuf:"bytes,1,opt,name=config,proto3" json:"config,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GenerateChangelog_Request) Reset() {
	*x = GenerateChangelog_Request{}
	mi := &file_pkg_generator_changelog_generator_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GenerateChangelog_Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GenerateChangelog_Request) ProtoMessage() {}

func (x *GenerateChangelog_Request) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_generator_changelog_generator_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GenerateChangelog_Request.ProtoReflect.Descriptor instead.
func (*GenerateChangelog_Request) Descriptor() ([]byte, []int) {
	return file_pkg_generator_changelog_generator_proto_rawDescGZIP(), []int{4, 0}
}

func (x *GenerateChangelog_Request) GetConfig() *ChangelogGeneratorConfig {
	if x != nil {
		return x.Config
	}
	return nil
}

type GenerateChangelog_Response struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Changelog     string                 `protobuf:"bytes,1,opt,name=changelog,proto3" json:"changelog,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GenerateChangelog_Response) Reset() {
	*x = GenerateChangelog_Response{}
	mi := &file_pkg_generator_changelog_generator_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GenerateChangelog_Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GenerateChangelog_Response) ProtoMessage() {}

func (x *GenerateChangelog_Response) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_generator_changelog_generator_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GenerateChangelog_Response.ProtoReflect.Descriptor instead.
func (*GenerateChangelog_Response) Descriptor() ([]byte, []int) {
	return file_pkg_generator_changelog_generator_proto_rawDescGZIP(), []int{4, 1}
}

func (x *GenerateChangelog_Response) GetChangelog() string {
	if x != nil {
		return x.Changelog
	}
	return ""
}

var File_pkg_generator_changelog_generator_proto protoreflect.FileDescriptor

const file_pkg_generator_changelog_generator_proto_rawDesc = "" +
	"\n" +
	"'pkg/generator/changelog_generator.proto\x1a\x18pkg/semrel/structs.proto\"\xc6\x01\n" +
	"\x16ChangelogGeneratorInit\x1a\x89\x01\n" +
	"\aRequest\x12C\n" +
	"\x06config\x18\x01 \x03(\v2+.ChangelogGeneratorInit.Request.ConfigEntryR\x06config\x1a9\n" +
	"\vConfigEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\x1a \n" +
	"\bResponse\x12\x14\n" +
	"\x05error\x18\x01 \x01(\tR\x05error\"C\n" +
	"\x16ChangelogGeneratorName\x1a\t\n" +
	"\aRequest\x1a\x1e\n" +
	"\bResponse\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\"L\n" +
	"\x19ChangelogGeneratorVersion\x1a\t\n" +
	"\aRequest\x1a$\n" +
	"\bResponse\x12\x18\n" +
	"\aversion\x18\x01 \x01(\tR\aversion\"\x8f\x01\n" +
	"\x18ChangelogGeneratorConfig\x12!\n" +
	"\acommits\x18\x01 \x03(\v2\a.CommitR\acommits\x12/\n" +
	"\x0elatest_release\x18\x02 \x01(\v2\b.ReleaseR\rlatestRelease\x12\x1f\n" +
	"\vnew_version\x18\x03 \x01(\tR\n" +
	"newVersion\"{\n" +
	"\x11GenerateChangelog\x1a<\n" +
	"\aRequest\x121\n" +
	"\x06config\x18\x01 \x01(\v2\x19.ChangelogGeneratorConfigR\x06config\x1a(\n" +
	"\bResponse\x12\x1c\n" +
	"\tchangelog\x18\x01 \x01(\tR\tchangelog2\xc9\x02\n" +
	"\x18ChangelogGeneratorPlugin\x12I\n" +
	"\x04Init\x12\x1f.ChangelogGeneratorInit.Request\x1a .ChangelogGeneratorInit.Response\x12I\n" +
	"\x04Name\x12\x1f.ChangelogGeneratorName.Request\x1a .ChangelogGeneratorName.Response\x12R\n" +
	"\aVersion\x12\".ChangelogGeneratorVersion.Request\x1a#.ChangelogGeneratorVersion.Response\x12C\n" +
	"\bGenerate\x12\x1a.GenerateChangelog.Request\x1a\x1b.GenerateChangelog.ResponseBBZ@github.com/go-semantic-release/semantic-release/v2/pkg/generatorb\x06proto3"

var (
	file_pkg_generator_changelog_generator_proto_rawDescOnce sync.Once
	file_pkg_generator_changelog_generator_proto_rawDescData []byte
)

func file_pkg_generator_changelog_generator_proto_rawDescGZIP() []byte {
	file_pkg_generator_changelog_generator_proto_rawDescOnce.Do(func() {
		file_pkg_generator_changelog_generator_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pkg_generator_changelog_generator_proto_rawDesc), len(file_pkg_generator_changelog_generator_proto_rawDesc)))
	})
	return file_pkg_generator_changelog_generator_proto_rawDescData
}

var file_pkg_generator_changelog_generator_proto_msgTypes = make([]protoimpl.MessageInfo, 14)
var file_pkg_generator_changelog_generator_proto_goTypes = []any{
	(*ChangelogGeneratorInit)(nil),             // 0: ChangelogGeneratorInit
	(*ChangelogGeneratorName)(nil),             // 1: ChangelogGeneratorName
	(*ChangelogGeneratorVersion)(nil),          // 2: ChangelogGeneratorVersion
	(*ChangelogGeneratorConfig)(nil),           // 3: ChangelogGeneratorConfig
	(*GenerateChangelog)(nil),                  // 4: GenerateChangelog
	(*ChangelogGeneratorInit_Request)(nil),     // 5: ChangelogGeneratorInit.Request
	(*ChangelogGeneratorInit_Response)(nil),    // 6: ChangelogGeneratorInit.Response
	nil,                                        // 7: ChangelogGeneratorInit.Request.ConfigEntry
	(*ChangelogGeneratorName_Request)(nil),     // 8: ChangelogGeneratorName.Request
	(*ChangelogGeneratorName_Response)(nil),    // 9: ChangelogGeneratorName.Response
	(*ChangelogGeneratorVersion_Request)(nil),  // 10: ChangelogGeneratorVersion.Request
	(*ChangelogGeneratorVersion_Response)(nil), // 11: ChangelogGeneratorVersion.Response
	(*GenerateChangelog_Request)(nil),          // 12: GenerateChangelog.Request
	(*GenerateChangelog_Response)(nil),         // 13: GenerateChangelog.Response
	(*semrel.Commit)(nil),                      // 14: Commit
	(*semrel.Release)(nil),                     // 15: Release
}
var file_pkg_generator_changelog_generator_proto_depIdxs = []int32{
	14, // 0: ChangelogGeneratorConfig.commits:type_name -> Commit
	15, // 1: ChangelogGeneratorConfig.latest_release:type_name -> Release
	7,  // 2: ChangelogGeneratorInit.Request.config:type_name -> ChangelogGeneratorInit.Request.ConfigEntry
	3,  // 3: GenerateChangelog.Request.config:type_name -> ChangelogGeneratorConfig
	5,  // 4: ChangelogGeneratorPlugin.Init:input_type -> ChangelogGeneratorInit.Request
	8,  // 5: ChangelogGeneratorPlugin.Name:input_type -> ChangelogGeneratorName.Request
	10, // 6: ChangelogGeneratorPlugin.Version:input_type -> ChangelogGeneratorVersion.Request
	12, // 7: ChangelogGeneratorPlugin.Generate:input_type -> GenerateChangelog.Request
	6,  // 8: ChangelogGeneratorPlugin.Init:output_type -> ChangelogGeneratorInit.Response
	9,  // 9: ChangelogGeneratorPlugin.Name:output_type -> ChangelogGeneratorName.Response
	11, // 10: ChangelogGeneratorPlugin.Version:output_type -> ChangelogGeneratorVersion.Response
	13, // 11: ChangelogGeneratorPlugin.Generate:output_type -> GenerateChangelog.Response
	8,  // [8:12] is the sub-list for method output_type
	4,  // [4:8] is the sub-list for method input_type
	4,  // [4:4] is the sub-list for extension type_name
	4,  // [4:4] is the sub-list for extension extendee
	0,  // [0:4] is the sub-list for field type_name
}

func init() { file_pkg_generator_changelog_generator_proto_init() }
func file_pkg_generator_changelog_generator_proto_init() {
	if File_pkg_generator_changelog_generator_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pkg_generator_changelog_generator_proto_rawDesc), len(file_pkg_generator_changelog_generator_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   14,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pkg_generator_changelog_generator_proto_goTypes,
		DependencyIndexes: file_pkg_generator_changelog_generator_proto_depIdxs,
		MessageInfos:      file_pkg_generator_changelog_generator_proto_msgTypes,
	}.Build()
	File_pkg_generator_changelog_generator_proto = out.File
	file_pkg_generator_changelog_generator_proto_goTypes = nil
	file_pkg_generator_changelog_generator_proto_depIdxs = nil
}
