// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.1
// source: pkg/semrel/structs.proto

package semrel

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RawCommit struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SHA           string                 `protobuf:"bytes,1,opt,name=SHA,proto3" json:"SHA,omitempty"`
	RawMessage    string                 `protobuf:"bytes,2,opt,name=raw_message,json=rawMessage,proto3" json:"raw_message,omitempty"`
	Annotations   map[string]string      `protobuf:"bytes,3,rep,name=annotations,proto3" json:"annotations,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RawCommit) Reset() {
	*x = RawCommit{}
	mi := &file_pkg_semrel_structs_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RawCommit) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RawCommit) ProtoMessage() {}

func (x *RawCommit) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_semrel_structs_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RawCommit.ProtoReflect.Descriptor instead.
func (*RawCommit) Descriptor() ([]byte, []int) {
	return file_pkg_semrel_structs_proto_rawDescGZIP(), []int{0}
}

func (x *RawCommit) GetSHA() string {
	if x != nil {
		return x.SHA
	}
	return ""
}

func (x *RawCommit) GetRawMessage() string {
	if x != nil {
		return x.RawMessage
	}
	return ""
}

func (x *RawCommit) GetAnnotations() map[string]string {
	if x != nil {
		return x.Annotations
	}
	return nil
}

type Change struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Major         bool                   `protobuf:"varint,1,opt,name=major,proto3" json:"major,omitempty"`
	Minor         bool                   `protobuf:"varint,2,opt,name=minor,proto3" json:"minor,omitempty"`
	Patch         bool                   `protobuf:"varint,3,opt,name=patch,proto3" json:"patch,omitempty"`
	Annotations   map[string]string      `protobuf:"bytes,4,rep,name=annotations,proto3" json:"annotations,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Change) Reset() {
	*x = Change{}
	mi := &file_pkg_semrel_structs_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Change) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Change) ProtoMessage() {}

func (x *Change) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_semrel_structs_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Change.ProtoReflect.Descriptor instead.
func (*Change) Descriptor() ([]byte, []int) {
	return file_pkg_semrel_structs_proto_rawDescGZIP(), []int{1}
}

func (x *Change) GetMajor() bool {
	if x != nil {
		return x.Major
	}
	return false
}

func (x *Change) GetMinor() bool {
	if x != nil {
		return x.Minor
	}
	return false
}

func (x *Change) GetPatch() bool {
	if x != nil {
		return x.Patch
	}
	return false
}

func (x *Change) GetAnnotations() map[string]string {
	if x != nil {
		return x.Annotations
	}
	return nil
}

type Commit struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SHA           string                 `protobuf:"bytes,1,opt,name=SHA,proto3" json:"SHA,omitempty"`
	Raw           []string               `protobuf:"bytes,2,rep,name=raw,proto3" json:"raw,omitempty"`
	Type          string                 `protobuf:"bytes,3,opt,name=type,proto3" json:"type,omitempty"`
	Scope         string                 `protobuf:"bytes,4,opt,name=scope,proto3" json:"scope,omitempty"`
	Message       string                 `protobuf:"bytes,5,opt,name=message,proto3" json:"message,omitempty"`
	Change        *Change                `protobuf:"bytes,6,opt,name=change,proto3" json:"change,omitempty"`
	Annotations   map[string]string      `protobuf:"bytes,7,rep,name=annotations,proto3" json:"annotations,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Commit) Reset() {
	*x = Commit{}
	mi := &file_pkg_semrel_structs_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Commit) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Commit) ProtoMessage() {}

func (x *Commit) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_semrel_structs_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Commit.ProtoReflect.Descriptor instead.
func (*Commit) Descriptor() ([]byte, []int) {
	return file_pkg_semrel_structs_proto_rawDescGZIP(), []int{2}
}

func (x *Commit) GetSHA() string {
	if x != nil {
		return x.SHA
	}
	return ""
}

func (x *Commit) GetRaw() []string {
	if x != nil {
		return x.Raw
	}
	return nil
}

func (x *Commit) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *Commit) GetScope() string {
	if x != nil {
		return x.Scope
	}
	return ""
}

func (x *Commit) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *Commit) GetChange() *Change {
	if x != nil {
		return x.Change
	}
	return nil
}

func (x *Commit) GetAnnotations() map[string]string {
	if x != nil {
		return x.Annotations
	}
	return nil
}

type Release struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SHA           string                 `protobuf:"bytes,1,opt,name=SHA,proto3" json:"SHA,omitempty"`
	Version       string                 `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`
	Annotations   map[string]string      `protobuf:"bytes,3,rep,name=annotations,proto3" json:"annotations,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Release) Reset() {
	*x = Release{}
	mi := &file_pkg_semrel_structs_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Release) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Release) ProtoMessage() {}

func (x *Release) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_semrel_structs_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Release.ProtoReflect.Descriptor instead.
func (*Release) Descriptor() ([]byte, []int) {
	return file_pkg_semrel_structs_proto_rawDescGZIP(), []int{3}
}

func (x *Release) GetSHA() string {
	if x != nil {
		return x.SHA
	}
	return ""
}

func (x *Release) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *Release) GetAnnotations() map[string]string {
	if x != nil {
		return x.Annotations
	}
	return nil
}

var File_pkg_semrel_structs_proto protoreflect.FileDescriptor

const file_pkg_semrel_structs_proto_rawDesc = "" +
	"\n" +
	"\x18pkg/semrel/structs.proto\"\xbd\x01\n" +
	"\tRawCommit\x12\x10\n" +
	"\x03SHA\x18\x01 \x01(\tR\x03SHA\x12\x1f\n" +
	"\vraw_message\x18\x02 \x01(\tR\n" +
	"rawMessage\x12=\n" +
	"\vannotations\x18\x03 \x03(\v2\x1b.RawCommit.AnnotationsEntryR\vannotations\x1a>\n" +
	"\x10AnnotationsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xc6\x01\n" +
	"\x06Change\x12\x14\n" +
	"\x05major\x18\x01 \x01(\bR\x05major\x12\x14\n" +
	"\x05minor\x18\x02 \x01(\bR\x05minor\x12\x14\n" +
	"\x05patch\x18\x03 \x01(\bR\x05patch\x12:\n" +
	"\vannotations\x18\x04 \x03(\v2\x18.Change.AnnotationsEntryR\vannotations\x1a>\n" +
	"\x10AnnotationsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\x8d\x02\n" +
	"\x06Commit\x12\x10\n" +
	"\x03SHA\x18\x01 \x01(\tR\x03SHA\x12\x10\n" +
	"\x03raw\x18\x02 \x03(\tR\x03raw\x12\x12\n" +
	"\x04type\x18\x03 \x01(\tR\x04type\x12\x14\n" +
	"\x05scope\x18\x04 \x01(\tR\x05scope\x12\x18\n" +
	"\amessage\x18\x05 \x01(\tR\amessage\x12\x1f\n" +
	"\x06change\x18\x06 \x01(\v2\a.ChangeR\x06change\x12:\n" +
	"\vannotations\x18\a \x03(\v2\x18.Commit.AnnotationsEntryR\vannotations\x1a>\n" +
	"\x10AnnotationsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xb2\x01\n" +
	"\aRelease\x12\x10\n" +
	"\x03SHA\x18\x01 \x01(\tR\x03SHA\x12\x18\n" +
	"\aversion\x18\x02 \x01(\tR\aversion\x12;\n" +
	"\vannotations\x18\x03 \x03(\v2\x19.Release.AnnotationsEntryR\vannotations\x1a>\n" +
	"\x10AnnotationsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01B?Z=github.com/go-semantic-release/semantic-release/v2/pkg/semrelb\x06proto3"

var (
	file_pkg_semrel_structs_proto_rawDescOnce sync.Once
	file_pkg_semrel_structs_proto_rawDescData []byte
)

func file_pkg_semrel_structs_proto_rawDescGZIP() []byte {
	file_pkg_semrel_structs_proto_rawDescOnce.Do(func() {
		file_pkg_semrel_structs_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pkg_semrel_structs_proto_rawDesc), len(file_pkg_semrel_structs_proto_rawDesc)))
	})
	return file_pkg_semrel_structs_proto_rawDescData
}

var file_pkg_semrel_structs_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_pkg_semrel_structs_proto_goTypes = []any{
	(*RawCommit)(nil), // 0: RawCommit
	(*Change)(nil),    // 1: Change
	(*Commit)(nil),    // 2: Commit
	(*Release)(nil),   // 3: Release
	nil,               // 4: RawCommit.AnnotationsEntry
	nil,               // 5: Change.AnnotationsEntry
	nil,               // 6: Commit.AnnotationsEntry
	nil,               // 7: Release.AnnotationsEntry
}
var file_pkg_semrel_structs_proto_depIdxs = []int32{
	4, // 0: RawCommit.annotations:type_name -> RawCommit.AnnotationsEntry
	5, // 1: Change.annotations:type_name -> Change.AnnotationsEntry
	1, // 2: Commit.change:type_name -> Change
	6, // 3: Commit.annotations:type_name -> Commit.AnnotationsEntry
	7, // 4: Release.annotations:type_name -> Release.AnnotationsEntry
	5, // [5:5] is the sub-list for method output_type
	5, // [5:5] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_pkg_semrel_structs_proto_init() }
func file_pkg_semrel_structs_proto_init() {
	if File_pkg_semrel_structs_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pkg_semrel_structs_proto_rawDesc), len(file_pkg_semrel_structs_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_pkg_semrel_structs_proto_goTypes,
		DependencyIndexes: file_pkg_semrel_structs_proto_depIdxs,
		MessageInfos:      file_pkg_semrel_structs_proto_msgTypes,
	}.Build()
	File_pkg_semrel_structs_proto = out.File
	file_pkg_semrel_structs_proto_goTypes = nil
	file_pkg_semrel_structs_proto_depIdxs = nil
}
